//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerComment
    {
        public int QuestionID { get; set; }
        public int UserID { get; set; }
        public int Comment { get; set; }
        public string Comments { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
