//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseSurvey
    {
        public int CourseID { get; set; }
        public int SurveyID { get; set; }
        public Nullable<int> BeforeCourseSurveyId { get; set; }
        public Nullable<int> InstructorsBeforeCourseSurveyid { get; set; }
        public Nullable<int> Instructorssurveyid { get; set; }
    }
}
