//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterinfo
    {
        public int ConfigID { get; set; }
        public int DefaultLoginType { get; set; }
        public string DefaultThankYouMessage { get; set; }
        public int SurveyExpirationPeriod { get; set; }
        public int AfterCourseReminderSend { get; set; }
        public string AfterCourseReminderSubject { get; set; }
        public string AfterCourseReminderBody { get; set; }
        public Nullable<int> allowviewtranscriptb4survey { get; set; }
    }
}
