//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
            this.AnswerMultiples = new HashSet<AnswerMultiple>();
            this.AnswerTextAreas = new HashSet<AnswerTextArea>();
        }
    
        public int QuestionID { get; set; }
        public int SurveyID { get; set; }
        public string Question1 { get; set; }
        public string Type { get; set; }
        public int NumAnswers { get; set; }
        public int Required { get; set; }
        public int Comments { get; set; }
        public int Position { get; set; }
    
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual ICollection<AnswerMultiple> AnswerMultiples { get; set; }
        public virtual ICollection<AnswerTextArea> AnswerTextAreas { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
