//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportRequest
    {
        public int ReportRequestID { get; set; }
        public string ReportName { get; set; }
        public string ReportFile { get; set; }
        public int SurveyID { get; set; }
        public int SortBy { get; set; }
        public int Multiple { get; set; }
        public string SchoolID { get; set; }
        public string DropDown { get; set; }
        public int checkbox1 { get; set; }
        public int ProcessID { get; set; }
        public int AdminID { get; set; }
        public int PercentageComplete { get; set; }
        public string FileName { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual Survey Survey { get; set; }
    }
}
