//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplementalQuestion
    {
        public int SupplementalQuestionID { get; set; }
        public int ConditionQuestionID { get; set; }
        public int ConditionAnswer { get; set; }
    }
}
