//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey
    {
        public Survey()
        {
            this.Questions = new HashSet<Question>();
            this.ReportRequests = new HashSet<ReportRequest>();
            this.ReportSettings = new HashSet<ReportSetting>();
            this.Users = new HashSet<User>();
        }
    
        public int SurveyID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int SurveyLoginType { get; set; }
        public string SurveyImage { get; set; }
        public Nullable<short> SurveyStatus { get; set; }
        public string SurveyCode { get; set; }
        public int DefaultSurvey { get; set; }
        public string SurveyThankYouMessage { get; set; }
        public int SurveyRequired { get; set; }
        public string AfterSurveyCertificate { get; set; }
        public string AfterSurveyEmailSubject { get; set; }
        public string AfterSurveyEmailBody { get; set; }
        public Nullable<int> instviewresult { get; set; }
        public Nullable<int> instviewcomment { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<ReportRequest> ReportRequests { get; set; }
        public virtual ICollection<ReportSetting> ReportSettings { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
