//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.Survey.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.AnswerComments = new HashSet<AnswerComment>();
            this.AnswerMultiples = new HashSet<AnswerMultiple>();
            this.AnswerTextAreas = new HashSet<AnswerTextArea>();
        }
    
        public int UserID { get; set; }
        public int GSMU_UserID { get; set; }
        public int CourseID { get; set; }
        public int SurveyID { get; set; }
        public System.DateTime DateInserted { get; set; }
    
        public virtual ICollection<AnswerComment> AnswerComments { get; set; }
        public virtual ICollection<AnswerMultiple> AnswerMultiples { get; set; }
        public virtual ICollection<AnswerTextArea> AnswerTextAreas { get; set; }
        public virtual Survey Survey { get; set; }
    }
}
