using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gsmu.Service.Models.School
{
    public class CourseModel
    {
        public int CourseId { get; set; }
        public string CourseNumber { get; set; }
        public string CourseName { get; set; }
        public decimal? DistPrice { get; set; }
        public decimal? NoDistPrice { get; set; }
        public string Location { get; set; }
        public string Locationurl { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Room { get; set; }
        public DateTime? Times { get; set; }
        public int? MaxEnroll { get; set; }
        public int? MaxWait { get; set; }
        public int? InstructorId { get; set; }
        public int? InstructorId2 { get; set; }
        public int? Instructorid3 { get; set; }
        public string Description { get; set; }
        public string MainCategory { get; set; }
        public string MainCategory2 { get; set; }
        public string Maincategory3 { get; set; }
        public string SubCategory1 { get; set; }
        public string Subcategory2 { get; set; }
        public string SubCategory1b { get; set; }
        public string SubCategory2b { get; set; }
        public string SubCategory1c { get; set; }
        public string SubCategory2c { get; set; }
        public string Materials { get; set; }
        public int? Days { get; set; }
        public double? CreditHours { get; set; }
        public byte? SubStatus { get; set; }
        public string NumSubsAvail { get; set; }
        public string EventNum { get; set; }
        public string AccountNum { get; set; }
        public short CancelCourse { get; set; }
        public int? EmailReminderType { get; set; }
        public string EmailReminderSubject { get; set; }
        public string EmailReminderBody { get; set; }
        public string Notes { get; set; }
        public short InternalClass { get; set; }
        public string PriceTypes { get; set; }
        public string NonPriceTypes { get; set; }
        public short DisplayPrice { get; set; }
        public short? MaterialsRequired { get; set; }
        public int? Audience { get; set; }
        public int AudienceID { get; set; }
        public short GradingSystem { get; set; }
        public short BuybackCourse { get; set; }
        public int DepartmentNameID { get; set; }
        public string StartEndTimeDisplay { get; set; }
        public double InserviceHours { get; set; }
        public string Icons { get; set; }
        public string LinkTitle { get; set; }
        public string LinkURL { get; set; }
        public string ExcludedOptions { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public int? CourseColorGrouping { get; set; }
        public string Special1 { get; set; }
        public string CourseCommentText { get; set; }
        public int courseoutlineid { get; set; }
        public int ShowTopCatalog { get; set; }
        public int ShowBoldCatalog { get; set; }
        public short AllowCreditRollover { get; set; }
        public double? CustomCreditHours { get; set; }
        public double? CEUCredit { get; set; }
        public double? GraduateCredit { get; set; }
        public short Requirements { get; set; }
        public int? OnlineCourse { get; set; }
        public string CustomCourseField1 { get; set; }
        public string CustomCourseField2 { get; set; }
        public int? HalfDayCourse { get; set; }
        public decimal? SpecialDistPrice1 { get; set; }
        public int Duplicated { get; set; }
        public DateTime? WaitListJobDate { get; set; }
        public int? SubSiteId { get; set; }
        public string ExternalKey { get; set; }
        public string SubSiteCourseImportKey { get; set; }
        public string CourseConfirmationEmailExtraText { get; set; }
        public short? ShowCreditRequirementLink { get; set; }
        public int? CourseCloseDays { get; set; }
        public DateTime? LastUpdateTime { get; set; }
        public int? Percent4MultiEnrollDiscount { get; set; }
        public int? MinStudentNum4MultiEnrollDiscount { get; set; }
        public string CustomCourseField3 { get; set; }
        public string CustomCourseField4 { get; set; }
        public string LocationAdditionalInfo { get; set; }
        public int? RoomDirectionsId { get; set; }
        public int? CoursesType { get; set; }
        public int? CollectExtraParticipant { get; set; }
        public string CourseInternalAccessCode { get; set; }
        public string CourseStudentInfoRequired { get; set; }
        public string OfflineStudentNames { get; set; }
        public int? Membership { get; set; }
        public int OfflineStudentCount { get; set; }
        public string LDAPGroupMatch { get; set; }
        public string ElectronicSignatureFile { get; set; }
        public string ElectronicSignatureFile2 { get; set; }
        public string ElectronicSignatureFile3 { get; set; }
        public string CourseTypeAltVerbiage { get; set; }
        public int? BBCourseCloned { get; set; }
        public int? CoursesHideFromCatalog { get; set; }
        public float? Optionalcredithours1 { get; set; }
        public int? ShowPrerequisite { get; set; }
        public string PrerequisiteInfo { get; set; }
        public int? RemindInstructor { get; set; }
        public string BBLastIntegrationState { get; set; }
        public DateTime? BBLastIntegrationDate { get; set; }
        public DateTime? BBastUpdateGrade { get; set; }
        public int? CourseCertificate { get; set; }
        public int? CourseSpecificEnrollmentCheck { get; set; }
        public int? ViewPastCoursesDays { get; set; }
        public string ShortDescription { get; set; }
        public short? SpecialCourseType { get; set; }
        public string CustomCourseField5 { get; set; }
        public string CustomCourseField6 { get; set; }
        public int? Mandatory { get; set; }
        public int? FreeClass { get; set; }
        public int? NoRegEmail { get; set; }
        public int? UseRoommateMatch { get; set; }
        public int? CourseType { get; set; }
        public int? EventId { get; set; }
        public int? SessionId { get; set; }
        public int? BBServer { get; set; }
        public int? BBAutoEnroll { get; set; }
        public int? ForImportOnly { get; set; }
        public string Country { get; set; }
        public string PartialPaymentAmount { get; set; }
        public string PartialPaymentSP { get; set; }
        public string PartialPaymentNon { get; set; }
        public DateTime? heliuslms_last_integration { get; set; }
        public int? heliuslmscloned { get; set; }
        public int? archived_course { get; set; }
        public string google_calendar { get; set; }
        public int? google_calendar_import_enable { get; set; }
        public int? StudentChoiceCourse { get; set; }
        public int? CourseCertificationsId { get; set; }
        public int? SendConfirmationEmailtoInstructor { get; set; }
        public string attendanceThreshold { get; set; }
        public int? MinMultiEnrolDiscountAll { get; set; }
        public string Amount4MultiEnrollDiscount { get; set; }
        public decimal? SingleCreditCost { get; set; }
        public double? Optionalcredithours2 { get; set; }
        public double? Optionalcredithours3 { get; set; }
        public double? Optionalcredithours4 { get; set; }
        public double? Optionalcredithours5 { get; set; }
        public double? Optionalcredithours6 { get; set; }
        public double? Optionalcredithours7 { get; set; }
        public double? Optionalcredithours8 { get; set; }
        public string CustomDropDownValueSequence { get; set; }
        public int? ShowCreditinPublic { get; set; }
        public int? AllowSendSurvey { get; set; }
        public string TileImageUrl { get; set; }
        public int? HaikuCourseId { get; set; }
        public string HaikuImportId { get; set; }
        public DateTime? HaikuIntegrationDate { get; set; }
        public DateTime? HaikuLastIntegrationDate { get; set; }
        public string HaikuLastResult { get; set; }
        public int? DisableHaikuiItegration { get; set; }
        public int? DisableCanvasIntegration { get; set; }
        public int? CanvasCourseId { get; set; }
        public string BBDateSyncInstructor { get; set; }
        public string BlackBoardDisk { get; set; }
        public string CourseConfiguration { get; set; }
    }
}
