//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildingDetail
    {
        public int BuildingDetailsId { get; set; }
        public int FloorId { get; set; }
        public string AdminEmail { get; set; }
        public string EquipManagerEmail { get; set; }
        public string CustodianEmail { get; set; }
    
        public virtual floor floor { get; set; }
    }
}
