//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FloorsScrollerConfig
    {
        public int FloorsScrollerConfigId { get; set; }
        public int FloorId { get; set; }
        public string ScrollerConfigValue { get; set; }
        public string footernote { get; set; }
    }
}
