//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class listing_countries
    {
        public listing_countries()
        {
            this.members = new HashSet<member>();
        }
    
        public int country_id { get; set; }
        public string country_name { get; set; }
    
        public virtual ICollection<member> members { get; set; }
    }
}
