//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class multi_days_booking
    {
        public int id { get; set; }
        public Nullable<System.DateTime> start_day { get; set; }
        public Nullable<System.DateTime> end_day { get; set; }
        public Nullable<int> type { get; set; }
        public short week_end { get; set; }
        public string Reminder1Sent { get; set; }
        public string Reminder2Sent { get; set; }
        public Nullable<int> AmountDue { get; set; }
        public string StudentUsername { get; set; }
        public Nullable<short> Billable { get; set; }
        public Nullable<System.DateTime> Printed { get; set; }
    }
}
