//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomEqApproval
    {
        public int approvalid { get; set; }
        public Nullable<int> multi_id { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public Nullable<int> approver { get; set; }
        public Nullable<int> approved { get; set; }
        public Nullable<System.DateTime> dateapproved { get; set; }
        public Nullable<System.DateTime> daterequest { get; set; }
        public Nullable<int> notifyadmin { get; set; }
    }
}
