//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSetup
    {
        public int SetupId { get; set; }
        public string SetupTitle { get; set; }
        public string SetupDescription { get; set; }
        public string SetupImageFileName { get; set; }
        public int SetupPlaces { get; set; }
        public int disabled { get; set; }
    }
}
