//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_booking
    {
        public int id { get; set; }
        public Nullable<System.DateTime> hour_start { get; set; }
        public Nullable<System.DateTime> hour_end { get; set; }
        public string title { get; set; }
        public string organization { get; set; }
        public string description { get; set; }
        public Nullable<int> room_id { get; set; }
        public short active { get; set; }
        public string member_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public Nullable<int> multi_id { get; set; }
        public short changed { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string CustomRoomSetupImageFilename { get; set; }
        public Nullable<int> RoomSetup { get; set; }
        public string RoomAudience { get; set; }
        public string RoomEquipment { get; set; }
        public Nullable<int> PeopleAttending { get; set; }
        public string PersonInCharge { get; set; }
        public string PersonInChargeEmail { get; set; }
        public string PersonInChargePhone { get; set; }
        public short displayPublic { get; set; }
        public Nullable<short> bookingType { get; set; }
        public Nullable<int> bookingTypeID { get; set; }
        public Nullable<short> AdminApproval { get; set; }
        public Nullable<short> EquipMgrApproval { get; set; }
        public Nullable<short> CustodianApproval { get; set; }
        public int IsNewRequest { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public int Archived { get; set; }
        public string extrainfoforuser { get; set; }
        public Nullable<int> sprequestapproved { get; set; }
        public Nullable<int> usagestatus { get; set; }
    
        public virtual room room { get; set; }
    }
}
