//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.RoomManagement.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public room()
        {
            this.room_booking = new HashSet<room_booking>();
        }
    
        public int id { get; set; }
        public string room_name { get; set; }
        public string room_description { get; set; }
        public Nullable<int> number_places { get; set; }
        public short active { get; set; }
        public string image { get; set; }
        public Nullable<int> floor_id { get; set; }
        public string RoomSetups { get; set; }
        public string RoomEquipment { get; set; }
        public string RoomManagers { get; set; }
        public Nullable<short> minSetupTime { get; set; }
        public Nullable<short> minTakedownTime { get; set; }
        public string PermitAdmin { get; set; }
        public string PermitSubAdmin { get; set; }
        public Nullable<int> subdivision_id { get; set; }
    
        public virtual floor floor { get; set; }
        public virtual ICollection<room_booking> room_booking { get; set; }
    }
}
