<!--#INCLUDE FILE="admin/ConnStr.asp"-->
<!--#INCLUDE FILE="admin/IncludeFunctions.asp"-->
<!--#INCLUDE FILE="admin/google/json.asp"-->
<%
 from_rubycall = true
function WriteToFile(FileName, Contents, Append)
on error resume next

if Append = true then
   iMode = 8
else
   iMode = 2
end if
set oFs = server.createobject("Scripting.FileSystemObject")
set oTextFile = oFs.OpenTextFile(FileName, iMode, True)
oTextFile.Write Contents
oTextFile.Close
set oTextFile = nothing
set oFS = nothing

end function


'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "rc: " & Request("rc") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "t: " & Request("t") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "ac: " & Request("ac") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "ap: " & Request("ap") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "desc: " & Request("x_description") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "x_amount: " & Request("x_amount") & vbcrlf, True

'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "x_response_code: " & Request("x_response_code") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "x_auth_code: " & Request("x_auth_code") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "x_trans_id: " & Request("x_trans_id") & vbcrlf, True
'WriteToFile "E:\websites\cssservices.gosignmeup.com\Test1.txt", "QueryString: " & Request.QueryString & vbcrlf, True



'Get custom field names and payment flags
Set rsMI = Server.CreateObject("ADODB.Recordset")
sql = "SELECT * FROM MasterInfo"
if session("MasterinfoId") > 0 then sql = sql & " where id = " & session("masterinfoid")
sql = sql & " order by subsiteid "
sql= sqlscrub(sql)
if session("debug") = "1" then response.write sql & "<br>"
session("lastsql") = sql
rsMI.Open sql, objconn, 3, 3


EmailAddress = rsMI("EmailAddress")
publicemailaddress = rsMI("PublicEmailAddress")
Session("publicemailaddress") = publicemailaddress

' Get from MasterInfo3
sql = "SELECT * FROM MasterInfo3 "
if session("masterinfo3id") > 0 then sql = sql & " where masterinfo3id = " &  session("masterinfo3id")
sql = sql & " order by subsiteid "
Set RSMI3 = Server.CreateObject("ADODB.Recordset")
sql= sqlscrub(sql)
if session("debug") = "1" then response.write sql & "<br>"
session("lastSQL") = sql
RSMI3.open sql, objConn, 3, 3
OnlineClasslabel = rsmi3("OnlineClasslabel")

'This is the key for the data we receive from Authorize.Net...
'rc= the response code. A 1 means a successful transaction. Anything else means the transaction was unsuccessful.
'type= “AUTH_CAPTURE”
'i= when we’re running these, i equals the primary key in our data.
't= the transaction id which is generated by Authourize.net which makes the transaction unique
'ac= the authorization code also generated by authorize.net
'ap= the amount paid. This will always match up with the price that you set in your form(s), assuming you’re sending the data using the format below (If you drop the link below into a browser you’ll see how it ends up at authorize.net):

payment_status = request("x_response_code")
transactionID = request("x_trans_id")
authnum = request("x_auth_code") 'authorization code
payment_gross = request("x_amount")
desc = request("x_description")

eBody = payment_status & " | " & transactionID & " | " & authnum & " | " & payment_gross & " | " & desc

'call sendemail(EmailAddress ,"lcpittman@gmail.com"  , "", "" , "Testing-Anet",eBody, Attachment)
if trim(desc) <>"" then
	iPos = Instr(desc, ":")
	order_number = request("x_invoice_num")
end if

dim filesys, filetxt
Const ForReading = 1, ForWriting = 2, ForAppending = 8
Set filesys = CreateObject("Scripting.FileSystemObject")
Set filetxt = filesys.OpenTextFile(Request.ServerVariables("APPL_PHYSICAL_PATH") & "\ErrorDump2.txt", ForAppending, True)
	filetxt.WriteLine("-----------------Begin Payment---------------")
	filetxt.WriteLine("0) Raw Data: " & desc & " -" )
	filetxt.WriteLine("1) Date: " & now() & " - " & request("x_type"))
	filetxt.WriteLine("2) Order# " & order_number & " -")
    filetxt.WriteLine("2a) invoice# " & request("x_invoice_num") & " -")
	filetxt.WriteLine("3) Payment Status #" & payment_status & " -")
	filetxt.WriteLine("4) Aut# " & authnum & " -")
	filetxt.WriteLine("4a) Tran# " & transactionID & " -")
	filetxt.WriteLine("5) Gross " & payment_gross & " -")

if trim(desc) <>"" and trim(lcase(request("x_type"))) = "auth_capture" then
	iPos = Instr(desc, ":")

	'order_number = Right(desc, Len(desc)-iPos)
	'iPos2 = Instr(order_number, "-")
	'response.write order_number & "---" & iPos2
	'order_number = Left(order_number, iPos2-1)
    order_number = request("x_invoice_num")
	if payment_status = "1" Then
		payment_status = "completed"
	elseif payment_status = "2" Then
		payment_status = "declined"
	else
		payment_status = "incomplete/declined"
	end if
	filetxt.WriteLine("4x) inside condition " & order_number & " -" & payment_status)
	'response.Write("desc: " & desc & "<br>")
	'response.Write("Order Number: " & order_number)
	'response.End()
	if trim(order_number)  = "" then order_number = order_number2
	filetxt.WriteLine("4x) inside condition " & order_number & " -" & payment_status)
	if trim(order_number) <> "" then
		filetxt.WriteLine("4x) inside condition " & order_number & " -" & payment_status)
		sSQL = "SELECT CR.RosterFrom,[Last], [First], email, CR.DATEADDED AS Paydate, CourseName, CR.CourseID AS CID, CR.StudentID AS SID FROM [Course Roster] CR INNER JOIN Students S ON S.StudentID=CR.StudentID "
		sSQL = sSQL & " INNER JOIN Courses C ON CR.CourseID=C.CourseID "
		sSQL = sSQL & " WHERE (CR.ordernumber = '" & order_number & "' or MasterOrderNumber='" & order_number & "') "
		Set rsStudOrderInfo = CreateObject("ADODB.RecordSet")
		rsStudOrderInfo.Open sSQL, objConn,3,3
				filetxt.WriteLine("4xx) inside condition " & order_number & " -" & payment_status)
		filetxt.WriteLine("5a) SQL Before " & sSQL & " -")
		filetxt.WriteLine("5aa) Return Count: " & rsStudOrderInfo.RecordCount & " -")
		If rsStudOrderInfo.RecordCount <> 0 Then
			payer_email = rsStudOrderInfo("email")
			first_name = rsStudOrderInfo("first")
			last_name = rsStudOrderInfo("last")
			item_name = rsStudOrderInfo("CourseName")
			payment_date = rsStudOrderInfo("Paydate")
			CourseID = rsStudOrderInfo("CID")
			StudentID = rsStudOrderInfo("SID")
			RosterFrom = rsStudOrderInfo("RosterFrom")-0


			defaultInfo = payer_email & " - " & first_name & " - " & last_name & " - " & payment_gross & " - Course Name: " & item_name
			SQLAudit = "Insert into AuditTrail ("
			SQLAudit = SQLAudit & "TableName,UserName,StudentID,CourseID,AuditDate,AuditAction,RoutineName,ShortDescription) Values ("
			SQLAudit = SQLAudit & "'course roster'"
			SQLAudit = SQLAudit & ",'" & order_number &"'"
			SQLAudit = SQLAudit & ",'" & StudentID
			SQLAudit = SQLAudit & "','" & CourseID
			SQLAudit = SQLAudit & "',getdate()"

			If trim(payment_status) = "completed" and rsStudOrderInfo.RecordCount > 0 and RosterFrom<>3 then
				response.write order_number & "*"
				SQLAudit = SQLAudit & ",'"& DBPrepValue(defaultInfo) &"'"
				uSQL = "Update [course roster] set cancel=0, paymethod='Credit Card', paidremainderamount=0, ChargeDate=getdate(), RespMsg='completed', totalpaid=" & payment_gross & ", paidinfull=-1 "
				uSQL = uSQL & ",paynumber='" & transactionID & "', authnum='" & authnum & "', RefNumber='" & authnum & "', result='completed' where ordernumber='" & order_number & "' or MasterOrderNumber='" & order_number & "'"
				Session("LastSQL") = uSQL
				objconn.execute(uSQL)
				filetxt.WriteLine("5a1) Update Roster SQL " & uSQL & " -")
			elseif trim(payment_status) = "refunded" and rsStudOrderInfo.RecordCount > 0 then
				dStatus  = 4
				SQLAudit = SQLAudit & ",'refunded'"
				filetxt.WriteLine("5a2) refunded payment -")
			elseif trim(payment_status) = "declined" and rsStudOrderInfo.RecordCount > 0 then
				dStatus = 0
				SQLAudit = SQLAudit & ",'Declined'"
				filetxt.WriteLine("5a3) Declined payment -")
			else
				dStatus = 0
				filetxt.WriteLine("5a4) unknown Payment -")
				SQLAudit = SQLAudit & ",'Unknown payment'"
			end if
			SQLAudit = SQLAudit & ",'anetconfirmed3.asp'"
			SQLAudit = SQLAudit & ",'Response Code: " & payment_status & "'"
			SQLAudit = SQLAudit & ")"
			objconn.execute(SQLAudit)
			filetxt.WriteLine("5b) AuditSQL " & SQLAudit & " -")
			if Session("publicemailaddress") = "" then Session("publicemailaddress") = "info@gosignmeup.com"
			If trim(payment_status) = "completed" and rsStudOrderInfo.RecordCount > 0  and RosterFrom<>3  then
				filetxt.WriteLine("5c) Sending Conf email ")
				call confirmation(3,order_number, StudentID)
			else
				'response.write "Status: " & payment_status & "<br>Code:" & request("x_response_code") & "<br><a href='javascript:history.goback(-1)'>Go Back</a>"
				'response.end
			end if

			''''''''''''''''''''' sending email.
			confirmedSubject = "Gosignmeup - Authorize.net Redirect Payment confirmation"
			confirmedBody = "Gosignmeup - Authorize.net Redirect Payment Detail" & vbcrlf & vbcrlf
			confirmedBody = confirmedBody & "Date: " & payment_date & vbcrlf
			confirmedBody = confirmedBody & "Order #: " & order_number & vbcrlf
			confirmedBody = confirmedBody & "Payment Status #: [ " & payment_status & " ]" & vbcrlf
			confirmedBody = confirmedBody & "Sender Name: " & first_name & " " & last_name & vbcrlf
			confirmedBody = confirmedBody & "Note: "& vbcrlf
			confirmedBody = confirmedBody & "Amount: $" & payment_gross & vbcrlf
			confirmedBody = confirmedBody & "------------ " & vbcrlf
			'call sendemail(EmailAddress ,EmailAddress  , "", "" , subject,emailbody, Attachment)
			'call sendemail(EmailAddress , "To"  , "", "" , confirmedSubject,confirmedBody, Attachment)
		else
			'Process Transcript Clock hours Payment.
			sqltranscript = "select * from ((Transcripts  TR INNER JOIN Students S ON S.StudentID=TR.StudentID)INNER JOIN [Course Roster] CR ON (CR.StudentId = TR.StudentID and Cr.courseid = tr.courseid)) where  TranscriptID ='"&order_number&"'"
			Set rsStudOrderHours = CreateObject("ADODB.RecordSet")
			rsStudOrderHours.Open sqltranscript, objConn,3,3
			If rsStudOrderHours.RecordCount <> 0 Then
				payer_email = rsStudOrderHours("email")
				first_name = rsStudOrderHours("first")
				last_name = rsStudOrderHours("last")
				item_name = rsStudOrderHours("CourseName")
				payment_date = FormatDateTime(Now(),2)
				CourseID = rsStudOrderHours("courseid")
				StudentID = rsStudOrderHours("StudentId")
				rosterid = rsStudOrderHours("rosterid")

				filetxt.WriteLine("6a) Transcript Found! -" & order_number & " - Count: " & rsStudOrderHours.RecordCount & " - Status: " & payment_status)

				defaultInfo = payer_email & " - " & first_name & " - " & last_name & " - " & payment_gross & " - Course Name: " & CourseID
				SQLAudit = "Insert into AuditTrail ("
				SQLAudit = SQLAudit & "TableName,UserName,StudentID,CourseID,AuditDate,AuditAction,RoutineName,ShortDescription) Values ("
				SQLAudit = SQLAudit & "'course roster'"
				SQLAudit = SQLAudit & ",'" & order_number &"'"
				SQLAudit = SQLAudit & ",'" & StudentID
				SQLAudit = SQLAudit & "','" & CourseID
				SQLAudit = SQLAudit & "',getdate()"

				If trim(payment_status) = "completed" and rsStudOrderHours.RecordCount > 0 then
					response.write order_number & "*"
					SQLAudit = SQLAudit & ",'"& DBPrepValue(defaultInfo) &"'"
						set dict = JSON.parse("{}")
						dict.set "Paydate", payment_date
						dict.set "AuthNum", authnum
						dict.set "TransactionID", transactionID
						dict.set "Amount", payment_gross
						jsontext = JSON.stringify(dict, nothing, 1)

						if len(jsontext) > 0 then
							jsontext = jsontext
						else
							jsontext = "{}"
						end if
					uSQL = "Update [Transcripts] set IsHoursPaid=1,IsHoursPaidInfo='"&jsontext&"' where TranscriptID ='"&order_number&"'"
					Session("LastSQL") = uSQL
					filetxt.WriteLine("6b) Update Transcript PRocess SQL " & uSQL & " -")
					objconn.execute(uSQL)
					uSQL = "Update [Course Roster] set IsHoursPaid=1 where rosterid ='"&rosterid&"'"
					Session("LastSQL") = uSQL
					objconn.execute(uSQL)
					filetxt.WriteLine("6b1) Update Transcript PRocess SQL " & uSQL & " -")
				elseif trim(payment_status) = "refunded" and rsStudOrderInfo.RecordCount > 0 then
					dStatus  = 4
					SQLAudit = SQLAudit & ",'refunded'"
					filetxt.WriteLine("6b2) Transcript refunded payment -")
				elseif trim(payment_status) = "declined" and rsStudOrderInfo.RecordCount > 0 then
					dStatus = 0
					SQLAudit = SQLAudit & ",'Declined'"
					filetxt.WriteLine("6b3) Transcript Declined payment -")
				else
					dStatus = 0
					filetxt.WriteLine("6b4) transcript unknown Payment -")
					SQLAudit = SQLAudit & ",'Unknown payment'"
				end if
				SQLAudit = SQLAudit & ",'silentformpost.asp'"
				SQLAudit = SQLAudit & ",'Response Code: " & payment_status & "'"
				SQLAudit = SQLAudit & ")"
			objconn.execute(SQLAudit)
		   end if
		end if

		filetxt.WriteLine("7) SQL " & sSQL & uSQL & " -")
		filetxt.WriteLine("-----------------End Payment---------------")

	end if
end if


filetxt.Close

%>