//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Gsmu.Api.TPGSecureLink {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TPGSecureLink", Namespace="http://service.secureLink.touchnet.com")]
    public partial class TPGSecureLink : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback generateSecureLinkTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback authorizeAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback adjustBalanceOperationCompleted;
        
        private System.Threading.SendOrPostCallback authorizeRecurringAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeRecurringAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback validateRecurringAccountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TPGSecureLink() {
            this.Url = global::Gsmu.Api.Properties.Settings.Default.Gsmu_Api_TPGSecureLink1_TPGSecureLink;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event generateSecureLinkTicketCompletedEventHandler generateSecureLinkTicketCompleted;
        
        /// <remarks/>
        public event authorizeAccountCompletedEventHandler authorizeAccountCompleted;
        
        /// <remarks/>
        public event adjustBalanceCompletedEventHandler adjustBalanceCompleted;
        
        /// <remarks/>
        public event authorizeRecurringAccountCompletedEventHandler authorizeRecurringAccountCompleted;
        
        /// <remarks/>
        public event removeRecurringAccountCompletedEventHandler removeRecurringAccountCompleted;
        
        /// <remarks/>
        public event validateRecurringAccountCompletedEventHandler validateRecurringAccountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("generateSecureLinkTicketResponse", Namespace="http://types.secureLink.touchnet.com")]
        public GenerateSecureLinkTicketResponse generateSecureLinkTicket([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] GenerateSecureLinkTicketRequest generateSecureLinkTicketRequest) {
            object[] results = this.Invoke("generateSecureLinkTicket", new object[] {
                        generateSecureLinkTicketRequest});
            return ((GenerateSecureLinkTicketResponse)(results[0]));
        }
        
        /// <remarks/>
        public void generateSecureLinkTicketAsync(GenerateSecureLinkTicketRequest generateSecureLinkTicketRequest) {
            this.generateSecureLinkTicketAsync(generateSecureLinkTicketRequest, null);
        }
        
        /// <remarks/>
        public void generateSecureLinkTicketAsync(GenerateSecureLinkTicketRequest generateSecureLinkTicketRequest, object userState) {
            if ((this.generateSecureLinkTicketOperationCompleted == null)) {
                this.generateSecureLinkTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OngenerateSecureLinkTicketOperationCompleted);
            }
            this.InvokeAsync("generateSecureLinkTicket", new object[] {
                        generateSecureLinkTicketRequest}, this.generateSecureLinkTicketOperationCompleted, userState);
        }
        
        private void OngenerateSecureLinkTicketOperationCompleted(object arg) {
            if ((this.generateSecureLinkTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.generateSecureLinkTicketCompleted(this, new generateSecureLinkTicketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("authorizeAccountResponse", Namespace="http://types.secureLink.touchnet.com")]
        public AuthorizeAccountResponse authorizeAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] AuthorizeAccountRequest authorizeAccountRequest) {
            object[] results = this.Invoke("authorizeAccount", new object[] {
                        authorizeAccountRequest});
            return ((AuthorizeAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void authorizeAccountAsync(AuthorizeAccountRequest authorizeAccountRequest) {
            this.authorizeAccountAsync(authorizeAccountRequest, null);
        }
        
        /// <remarks/>
        public void authorizeAccountAsync(AuthorizeAccountRequest authorizeAccountRequest, object userState) {
            if ((this.authorizeAccountOperationCompleted == null)) {
                this.authorizeAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthorizeAccountOperationCompleted);
            }
            this.InvokeAsync("authorizeAccount", new object[] {
                        authorizeAccountRequest}, this.authorizeAccountOperationCompleted, userState);
        }
        
        private void OnauthorizeAccountOperationCompleted(object arg) {
            if ((this.authorizeAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authorizeAccountCompleted(this, new authorizeAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void adjustBalance([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] AdjustBalanceRequest adjustBalanceRequest) {
            this.Invoke("adjustBalance", new object[] {
                        adjustBalanceRequest});
        }
        
        /// <remarks/>
        public void adjustBalanceAsync(AdjustBalanceRequest adjustBalanceRequest) {
            this.adjustBalanceAsync(adjustBalanceRequest, null);
        }
        
        /// <remarks/>
        public void adjustBalanceAsync(AdjustBalanceRequest adjustBalanceRequest, object userState) {
            if ((this.adjustBalanceOperationCompleted == null)) {
                this.adjustBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnadjustBalanceOperationCompleted);
            }
            this.InvokeAsync("adjustBalance", new object[] {
                        adjustBalanceRequest}, this.adjustBalanceOperationCompleted, userState);
        }
        
        private void OnadjustBalanceOperationCompleted(object arg) {
            if ((this.adjustBalanceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.adjustBalanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("authorizeRecurringAccountResponse", Namespace="http://types.secureLink.touchnet.com")]
        public AuthorizeRecurringAccountResponse authorizeRecurringAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] AuthorizeRecurringAccountRequest authorizeRecurringAccountRequest) {
            object[] results = this.Invoke("authorizeRecurringAccount", new object[] {
                        authorizeRecurringAccountRequest});
            return ((AuthorizeRecurringAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void authorizeRecurringAccountAsync(AuthorizeRecurringAccountRequest authorizeRecurringAccountRequest) {
            this.authorizeRecurringAccountAsync(authorizeRecurringAccountRequest, null);
        }
        
        /// <remarks/>
        public void authorizeRecurringAccountAsync(AuthorizeRecurringAccountRequest authorizeRecurringAccountRequest, object userState) {
            if ((this.authorizeRecurringAccountOperationCompleted == null)) {
                this.authorizeRecurringAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnauthorizeRecurringAccountOperationCompleted);
            }
            this.InvokeAsync("authorizeRecurringAccount", new object[] {
                        authorizeRecurringAccountRequest}, this.authorizeRecurringAccountOperationCompleted, userState);
        }
        
        private void OnauthorizeRecurringAccountOperationCompleted(object arg) {
            if ((this.authorizeRecurringAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.authorizeRecurringAccountCompleted(this, new authorizeRecurringAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void removeRecurringAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] RemoveRecurringAccountRequest removeRecurringAccountRequest) {
            this.Invoke("removeRecurringAccount", new object[] {
                        removeRecurringAccountRequest});
        }
        
        /// <remarks/>
        public void removeRecurringAccountAsync(RemoveRecurringAccountRequest removeRecurringAccountRequest) {
            this.removeRecurringAccountAsync(removeRecurringAccountRequest, null);
        }
        
        /// <remarks/>
        public void removeRecurringAccountAsync(RemoveRecurringAccountRequest removeRecurringAccountRequest, object userState) {
            if ((this.removeRecurringAccountOperationCompleted == null)) {
                this.removeRecurringAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveRecurringAccountOperationCompleted);
            }
            this.InvokeAsync("removeRecurringAccount", new object[] {
                        removeRecurringAccountRequest}, this.removeRecurringAccountOperationCompleted, userState);
        }
        
        private void OnremoveRecurringAccountOperationCompleted(object arg) {
            if ((this.removeRecurringAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeRecurringAccountCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("validateRecurringAccountResponse", Namespace="http://types.secureLink.touchnet.com")]
        public ValidateRecurringAccountResponse validateRecurringAccount([System.Xml.Serialization.XmlElementAttribute(Namespace="http://types.secureLink.touchnet.com")] ValidateRecurringAccountRequest validateRecurringAccountRequest) {
            object[] results = this.Invoke("validateRecurringAccount", new object[] {
                        validateRecurringAccountRequest});
            return ((ValidateRecurringAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void validateRecurringAccountAsync(ValidateRecurringAccountRequest validateRecurringAccountRequest) {
            this.validateRecurringAccountAsync(validateRecurringAccountRequest, null);
        }
        
        /// <remarks/>
        public void validateRecurringAccountAsync(ValidateRecurringAccountRequest validateRecurringAccountRequest, object userState) {
            if ((this.validateRecurringAccountOperationCompleted == null)) {
                this.validateRecurringAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateRecurringAccountOperationCompleted);
            }
            this.InvokeAsync("validateRecurringAccount", new object[] {
                        validateRecurringAccountRequest}, this.validateRecurringAccountOperationCompleted, userState);
        }
        
        private void OnvalidateRecurringAccountOperationCompleted(object arg) {
            if ((this.validateRecurringAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateRecurringAccountCompleted(this, new validateRecurringAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class GenerateSecureLinkTicketRequest {
        
        private string ticketNameField;
        
        private nameValuePair[] nameValuePairsField;
        
        /// <remarks/>
        public string ticketName {
            get {
                return this.ticketNameField;
            }
            set {
                this.ticketNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nameValuePairs")]
        public nameValuePair[] nameValuePairs {
            get {
                return this.nameValuePairsField;
            }
            set {
                this.nameValuePairsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class nameValuePair {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class ValidateRecurringAccountResponse {
        
        private bool validField;
        
        private string pmtMethodExpDateField;
        
        /// <remarks/>
        public bool valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
            }
        }
        
        /// <remarks/>
        public string pmtMethodExpDate {
            get {
                return this.pmtMethodExpDateField;
            }
            set {
                this.pmtMethodExpDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class ValidateRecurringAccountRequest {
        
        private string sessionField;
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class RemoveRecurringAccountRequest {
        
        private string sessionField;
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AuthorizeRecurringAccountResponse {
        
        private AchMakePaymentResponse achResponseField;
        
        private CreditCardAuthResponse creditResponseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AchMakePaymentResponse achResponse {
            get {
                return this.achResponseField;
            }
            set {
                this.achResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CreditCardAuthResponse creditResponse {
            get {
                return this.creditResponseField;
            }
            set {
                this.creditResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AchMakePaymentResponse {
        
        private string receiptNumberField;
        
        private string agreementNumberField;
        
        private string bankNameField;
        
        private string bankAddressField;
        
        private string bankCityStateZipField;
        
        private string maskedAccountNumberField;
        
        /// <remarks/>
        public string receiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string agreementNumber {
            get {
                return this.agreementNumberField;
            }
            set {
                this.agreementNumberField = value;
            }
        }
        
        /// <remarks/>
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string bankAddress {
            get {
                return this.bankAddressField;
            }
            set {
                this.bankAddressField = value;
            }
        }
        
        /// <remarks/>
        public string bankCityStateZip {
            get {
                return this.bankCityStateZipField;
            }
            set {
                this.bankCityStateZipField = value;
            }
        }
        
        /// <remarks/>
        public string maskedAccountNumber {
            get {
                return this.maskedAccountNumberField;
            }
            set {
                this.maskedAccountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class CreditCardAuthResponse {
        
        private string approvalCodeField;
        
        private string receiptNumberField;
        
        private bool cvv2AvailableField;
        
        private bool cvv2SucceededField;
        
        private bool avsAvailableField;
        
        private bool avsSucceededField;
        
        private bool avsZipStatusField;
        
        private bool avsAddrStatusField;
        
        private StoreCreditCardInfoResponse creditCardInfoField;
        
        /// <remarks/>
        public string approvalCode {
            get {
                return this.approvalCodeField;
            }
            set {
                this.approvalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string receiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool cvv2Available {
            get {
                return this.cvv2AvailableField;
            }
            set {
                this.cvv2AvailableField = value;
            }
        }
        
        /// <remarks/>
        public bool cvv2Succeeded {
            get {
                return this.cvv2SucceededField;
            }
            set {
                this.cvv2SucceededField = value;
            }
        }
        
        /// <remarks/>
        public bool avsAvailable {
            get {
                return this.avsAvailableField;
            }
            set {
                this.avsAvailableField = value;
            }
        }
        
        /// <remarks/>
        public bool avsSucceeded {
            get {
                return this.avsSucceededField;
            }
            set {
                this.avsSucceededField = value;
            }
        }
        
        /// <remarks/>
        public bool avsZipStatus {
            get {
                return this.avsZipStatusField;
            }
            set {
                this.avsZipStatusField = value;
            }
        }
        
        /// <remarks/>
        public bool avsAddrStatus {
            get {
                return this.avsAddrStatusField;
            }
            set {
                this.avsAddrStatusField = value;
            }
        }
        
        /// <remarks/>
        public StoreCreditCardInfoResponse creditCardInfo {
            get {
                return this.creditCardInfoField;
            }
            set {
                this.creditCardInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class StoreCreditCardInfoResponse {
        
        private string creditCardTypeField;
        
        private string maskedAccountNumberField;
        
        /// <remarks/>
        public string creditCardType {
            get {
                return this.creditCardTypeField;
            }
            set {
                this.creditCardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string maskedAccountNumber {
            get {
                return this.maskedAccountNumberField;
            }
            set {
                this.maskedAccountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AuthorizeRecurringAccountRequest {
        
        private string sessionField;
        
        private long amountField;
        
        private string ancillaryDataField;
        
        private string applicationField;
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
        
        /// <remarks/>
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ancillaryData {
            get {
                return this.ancillaryDataField;
            }
            set {
                this.ancillaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AdjustBalanceRequest {
        
        private string sessionField;
        
        private string receiptNumberField;
        
        private long amountField;
        
        private string ancillaryDataField;
        
        private string applicationField;
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
        
        /// <remarks/>
        public string receiptNumber {
            get {
                return this.receiptNumberField;
            }
            set {
                this.receiptNumberField = value;
            }
        }
        
        /// <remarks/>
        public long amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ancillaryData {
            get {
                return this.ancillaryDataField;
            }
            set {
                this.ancillaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AuthorizeAccountResponse {
        
        private string ticketNameField;
        
        private nameValuePair[] nameValuePairsField;
        
        private AchMakePaymentResponse achResponseField;
        
        private CreditCardAuthResponse creditResponseField;
        
        /// <remarks/>
        public string ticketName {
            get {
                return this.ticketNameField;
            }
            set {
                this.ticketNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("nameValuePairs")]
        public nameValuePair[] nameValuePairs {
            get {
                return this.nameValuePairsField;
            }
            set {
                this.nameValuePairsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AchMakePaymentResponse achResponse {
            get {
                return this.achResponseField;
            }
            set {
                this.achResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CreditCardAuthResponse creditResponse {
            get {
                return this.creditResponseField;
            }
            set {
                this.creditResponseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class ApplicationSpecificLogData {
        
        private string nameField;
        
        private string valueField;
        
        private ApplicationSpecificLogData[] childrenField;
        
        private ApplicationSpecificLogData[] attributesField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("children")]
        public ApplicationSpecificLogData[] children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes")]
        public ApplicationSpecificLogData[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class AuthorizeAccountRequest {
        
        private string sessionField;
        
        private string invoiceNumberField;
        
        private string ancillaryDataField;
        
        private string applicationField;
        
        private ApplicationSpecificLogData[] logDataField;
        
        /// <remarks/>
        public string session {
            get {
                return this.sessionField;
            }
            set {
                this.sessionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ancillaryData {
            get {
                return this.ancillaryDataField;
            }
            set {
                this.ancillaryDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string application {
            get {
                return this.applicationField;
            }
            set {
                this.applicationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("logData")]
        public ApplicationSpecificLogData[] logData {
            get {
                return this.logDataField;
            }
            set {
                this.logDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://types.secureLink.touchnet.com")]
    public partial class GenerateSecureLinkTicketResponse {
        
        private string ticketField;
        
        private System.DateTime ticketExpireField;
        
        /// <remarks/>
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ticketExpire {
            get {
                return this.ticketExpireField;
            }
            set {
                this.ticketExpireField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void generateSecureLinkTicketCompletedEventHandler(object sender, generateSecureLinkTicketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class generateSecureLinkTicketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal generateSecureLinkTicketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GenerateSecureLinkTicketResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GenerateSecureLinkTicketResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void authorizeAccountCompletedEventHandler(object sender, authorizeAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorizeAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authorizeAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthorizeAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthorizeAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void adjustBalanceCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void authorizeRecurringAccountCompletedEventHandler(object sender, authorizeRecurringAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorizeRecurringAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal authorizeRecurringAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AuthorizeRecurringAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AuthorizeRecurringAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void removeRecurringAccountCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void validateRecurringAccountCompletedEventHandler(object sender, validateRecurringAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateRecurringAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateRecurringAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ValidateRecurringAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ValidateRecurringAccountResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591