//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdHocReportTemplate
    {
        public int AdHocReportTemplatesId { get; set; }
        public string ReportDetails { get; set; }
        public string ReportTitle { get; set; }
        public string ReportEmailAddress { get; set; }
        public Nullable<int> ReportExcludeCancelled { get; set; }
        public Nullable<int> ReportNumber { get; set; }
        public Nullable<System.DateTime> datelastsent { get; set; }
        public Nullable<int> isroutine { get; set; }
        public Nullable<System.DateTime> datelastexport { get; set; }
    }
}
