//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdministratorReportView
    {
        public Nullable<int> STUDENTID { get; set; }
        public int RosterID { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public string StudentName { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> SCHOOL { get; set; }
        public Nullable<int> InActive { get; set; }
        public short WAITING { get; set; }
        public short crattended { get; set; }
        public short Cancel { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> TIMEADDED { get; set; }
        public string StudentGrade { get; set; }
        public string CourseCost { get; set; }
        public Nullable<int> COURSEID { get; set; }
        public string COURSENUM { get; set; }
        public string COURSENAME { get; set; }
        public string courseLocation { get; set; }
        public string schoolName { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public Nullable<int> INSTRUCTORID { get; set; }
        public Nullable<int> INSTRUCTORID2 { get; set; }
        public Nullable<int> INSTRUCTORID3 { get; set; }
        public string gradelevel { get; set; }
        public string InstrctrName1 { get; set; }
        public string InstrctrLast1 { get; set; }
        public string InstrctrName2 { get; set; }
        public string InstrctrLast2 { get; set; }
        public string InstrctrName3 { get; set; }
        public string InstrctrLast3 { get; set; }
        public string DISTRICT { get; set; }
        public string StudRegField1 { get; set; }
        public string StudRegField2 { get; set; }
        public string StudRegField3 { get; set; }
        public string StudRegField4 { get; set; }
        public string StudRegField5 { get; set; }
        public string StudRegField6 { get; set; }
        public string StudRegField7 { get; set; }
        public string StudRegField8 { get; set; }
        public string StudRegField9 { get; set; }
        public string StudRegField10 { get; set; }
        public string StudRegField11 { get; set; }
        public string StudRegField12 { get; set; }
        public string StudRegField13 { get; set; }
        public string StudRegField14 { get; set; }
        public string StudRegField15 { get; set; }
        public string StudRegField16 { get; set; }
        public string StudRegField17 { get; set; }
        public string StudRegField18 { get; set; }
        public string StudRegField19 { get; set; }
        public string StudRegField20 { get; set; }
        public Nullable<System.DateTime> coursedate { get; set; }
        public Nullable<double> RosterCreditHours { get; set; }
        public Nullable<double> InserviceHours { get; set; }
        public Nullable<float> GraduateCredit { get; set; }
        public Nullable<double> CustomCreditHours { get; set; }
        public string SupvFirstname { get; set; }
        public string SupvSurname { get; set; }
        public string SupvName { get; set; }
        public Nullable<int> StudentDistrict { get; set; }
        public Nullable<float> Optionalcredithours1 { get; set; }
        public Nullable<double> Optionalcredithours2 { get; set; }
        public Nullable<double> Optionalcredithours3 { get; set; }
        public Nullable<double> Optionalcredithours4 { get; set; }
        public Nullable<double> Optionalcredithours5 { get; set; }
    }
}
