//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceView
    {
        public int RosterID { get; set; }
        public Nullable<int> Attended { get; set; }
        public Nullable<double> AttendedHours { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<double> TotalAttendedHours { get; set; }
    }
}
