//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceDetail
    {
        public int AttendanceDetailId { get; set; }
        public int CourseID { get; set; }
        public int RosterId { get; set; }
        public System.DateTime CourseDate { get; set; }
        public int Attended { get; set; }
        public Nullable<float> AttendedHours { get; set; }
    
        public virtual Course_Roster Course_Roster { get; set; }
        public virtual Course Cours { get; set; }
    }
}
