//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        public int AuditID { get; set; }
        public string TableName { get; set; }
        public string UserName { get; set; }
        public int StudentID { get; set; }
        public int CourseID { get; set; }
        public System.DateTime AuditDate { get; set; }
        public string AuditAction { get; set; }
        public string RoutineName { get; set; }
        public string ShortDescription { get; set; }
        public string DetailDescription { get; set; }
        public string ATErrorMsg { get; set; }
    }
}
