//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoReserveCourse
    {
        public System.Guid ReservationId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<System.DateTime> ExpiredTime { get; set; }
        public int id { get; set; }
    }
}
