//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackgroundProcessRequest
    {
        public Nullable<System.DateTime> ProcRequestdate { get; set; }
        public string procReqDetail { get; set; }
        public string procReqType { get; set; }
        public Nullable<int> procReqStatus { get; set; }
        public int procRequestID { get; set; }
        public Nullable<int> procCourseID { get; set; }
    }
}
