//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackboardServersInfo
    {
        public int bbserverid { get; set; }
        public string BlackboardConnectionUrl { get; set; }
        public string BlackboardGradeCenterColumnName { get; set; }
        public string BlackboardCourseRole { get; set; }
        public string BlackboardGradeColumnValueFailed { get; set; }
        public string BlackboardPortalSecRole { get; set; }
        public string BlackboardPortalRole { get; set; }
        public string BlackboardInstructorRole { get; set; }
        public string BlackboardGradeCenterColumnValue { get; set; }
        public string bb_time_difference_from_gsmu { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string BBServername { get; set; }
        public Nullable<int> ServerReady { get; set; }
    }
}
