//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackboardUserRole
    {
        public int roleidx { get; set; }
        public Nullable<int> roletype { get; set; }
        public Nullable<int> studentid { get; set; }
        public string BBRoleID { get; set; }
        public string BBRoleName { get; set; }
        public Nullable<int> exclusion { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<int> districtid { get; set; }
        public Nullable<int> defaultPortalRole { get; set; }
    }
}
