//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackboardLog
    {
        public int BlackboardLogId { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string integration_type { get; set; }
        public int level { get; set; }
        public string result { get; set; }
        public string error { get; set; }
        public string exception { get; set; }
        public string message { get; set; }
        public string debug { get; set; }
    }
}
