//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificationsStudentCompleted
    {
        public int CertificationsStudentCompletedId { get; set; }
        public Nullable<int> CertificationsId { get; set; }
        public string CertificationsTitle { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CompletionBasedOn { get; set; }
        public Nullable<System.DateTime> QualificationStartDate { get; set; }
        public Nullable<int> CertificationsStudentId { get; set; }
    
        public virtual Certification Certification { get; set; }
        public virtual Student Student { get; set; }
    }
}
