//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CitrixLog
    {
        public int CitrixLogId { get; set; }
        public Nullable<System.DateTime> entry_date { get; set; }
        public string integration_type { get; set; }
        public int loglevel { get; set; }
        public string callresult { get; set; }
        public string callmessage { get; set; }
        public string callerror { get; set; }
    }
}
