//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public int ccodeid { get; set; }
        public string countrycode { get; set; }
        public string countryname { get; set; }
        public Nullable<int> disabled { get; set; }
        public Nullable<int> countryorder { get; set; }
    }
}
