//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coupon
    {
        public int CouponId { get; set; }
        public string CouponCode { get; set; }
        public Nullable<float> CouponPercentAmount { get; set; }
        public Nullable<float> CouponDollarAmount { get; set; }
        public Nullable<System.DateTime> CouponStartDate { get; set; }
        public Nullable<System.DateTime> CouponExpireDate { get; set; }
        public Nullable<int> CouponCourseId { get; set; }
        public Nullable<int> CouponOneTimeUse { get; set; }
        public Nullable<int> CouponMaterialsDiscounted { get; set; }
        public Nullable<float> CouponPerCourseAmount { get; set; }
        public string additionalcourseid { get; set; }
        public Nullable<int> CouponAutomatic { get; set; }
        public Nullable<int> CouponOrderCourses { get; set; }
        public Nullable<int> NoOfCouponAvailable { get; set; }
        public Nullable<int> LimitCouponUsageinSystem { get; set; }
    }
}
