//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseCategory
    {
        public int CourseCategoryID { get; set; }
        public string CourseCategoryColor { get; set; }
        public string CourseCategoryName { get; set; }
        public short registrationlimit { get; set; }
    }
}
