//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseOutline
    {
        public int CourseOutlineID { get; set; }
        public int CourseId { get; set; }
        public string Outline { get; set; }
        public string CourseOutlineTitle { get; set; }
        public string CourseOutlineUpload { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
