//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class coursearchive
    {
        public int archIDX { get; set; }
        public int courseID { get; set; }
        public string fieldname { get; set; }
        public string fieldvalue { get; set; }
        public int datatype { get; set; }
        public int datatypesize { get; set; }
    }
}
