//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesGridComn
    {
        public short CANCELCOURSE { get; set; }
        public int COURSEID { get; set; }
        public string COURSENAME { get; set; }
        public string COURSENUM { get; set; }
        public string LOCATION { get; set; }
        public short InternalClass { get; set; }
        public Nullable<int> INSTRUCTORID { get; set; }
        public Nullable<int> INSTRUCTORID2 { get; set; }
        public Nullable<int> INSTRUCTORID3 { get; set; }
        public Nullable<int> CourseCloseDays { get; set; }
        public string description { get; set; }
        public string i1first { get; set; }
        public string i1last { get; set; }
        public string i2first { get; set; }
        public string i2last { get; set; }
        public string i3first { get; set; }
        public string i3last { get; set; }
        public Nullable<System.DateTime> coursestart { get; set; }
        public Nullable<System.DateTime> coursedate { get; set; }
        public Nullable<System.DateTime> coursetime { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string SubSubCategory { get; set; }
        public Nullable<int> coursetype { get; set; }
        public Nullable<int> viewpastcoursesdays { get; set; }
        public Nullable<int> OnlineCourse { get; set; }
        public Nullable<System.DateTime> passcoursedate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string LOCATIONURL { get; set; }
        public string courseinternalaccesscode { get; set; }
        public Nullable<decimal> DISTPRICE { get; set; }
        public Nullable<decimal> NODISTPRICE { get; set; }
        public Nullable<int> eventid { get; set; }
        public string MainCategoryId { get; set; }
        public string SubCategoryId { get; set; }
        public string SubSubCategoryId { get; set; }
        public Nullable<double> CREDITHOURS { get; set; }
        public string ACCOUNTNUM { get; set; }
        public Nullable<int> MAXENROLL { get; set; }
        public Nullable<int> MAXWAIT { get; set; }
        public string ROOM { get; set; }
        public Nullable<int> DAYS { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public Nullable<System.DateTime> Expr1 { get; set; }
        public Nullable<System.DateTime> Expr2 { get; set; }
    }
}
