//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_Roster
    {
        public Course_Roster()
        {
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
            this.rostermaterials = new HashSet<rostermaterial>();
            this.CourseExtraParticipants = new HashSet<CourseExtraParticipant>();
        }
    
        public int RosterID { get; set; }
        public Nullable<int> COURSEID { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> TIMEADDED { get; set; }
        public short WAITING { get; set; }
        public Nullable<short> WaitOrder { get; set; }
        public short ATTENDED { get; set; }
        public short DIDNTATTEND { get; set; }
        public Nullable<double> HOURS { get; set; }
        public string CourseCost { get; set; }
        public string PAYMETHOD { get; set; }
        public string payNumber { get; set; }
        public string CardName { get; set; }
        public string CardAddress { get; set; }
        public string CardNumber { get; set; }
        public string CardExp { get; set; }
        public string AuthNum { get; set; }
        public string OrderNumber { get; set; }
        public string CancelNumber { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string PaymentNotes { get; set; }
        public Nullable<System.DateTime> ReminderSent { get; set; }
        public Nullable<System.DateTime> Reminder2Sent { get; set; }
        public short Cancel { get; set; }
        public short PaidInFull { get; set; }
        public string Position { get; set; }
        public string Job { get; set; }
        public Nullable<System.DateTime> ChargeDate { get; set; }
        public string RefNumber { get; set; }
        public string RespMsg { get; set; }
        public string Result { get; set; }
        public string StudentGrade { get; set; }
        public string PricingOption { get; set; }
        public short PricingMember { get; set; }
        public Nullable<double> InserviceHours { get; set; }
        public string CourseHoursType { get; set; }
        public string CreditApplied { get; set; }
        public int ExternalDBUpdated { get; set; }
        public decimal CourseSalesTaxPaid { get; set; }
        public int OptionalInfo1 { get; set; }
        public int OptionalInfo2A { get; set; }
        public int OptionalInfo2B { get; set; }
        public int OptionalInfo2C { get; set; }
        public int OptionalInfo2D { get; set; }
        public int OptionalInfo2E { get; set; }
        public int OptionalInfo2F { get; set; }
        public int OptionalInfo2G { get; set; }
        public short Rebill { get; set; }
        public string CheckoutComments { get; set; }
        public int CreditedInFull { get; set; }
        public Nullable<double> CustomCreditHours { get; set; }
        public string CouponCode { get; set; }
        public Nullable<float> CouponDiscount { get; set; }
        public string CouponDetails { get; set; }
        public Nullable<int> NoTaxShipping { get; set; }
        public string CouponNittyGritty { get; set; }
        public Nullable<float> ceucredit { get; set; }
        public Nullable<float> graduatecredit { get; set; }
        public Nullable<int> Parking { get; set; }
        public string SubstituteName { get; set; }
        public string CRInitialAuditInfo { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
        public int originalstudentid { get; set; }
        public System.DateTime laststudentreplacetime { get; set; }
        public string IHTAccountNumber { get; set; }
        public string IHTCreditAccountNumber { get; set; }
        public string IHTDebitApprovedby { get; set; }
        public string MasterOrderNumber { get; set; }
        public Nullable<int> AllowModifyMultiEnroll { get; set; }
        public Nullable<int> EnrollMaster { get; set; }
        public System.DateTime SAPBookingMade { get; set; }
        public System.DateTime SAPBookingCancelled { get; set; }
        public string ExtraParticipant { get; set; }
        public string OptionalCollectedInfo1 { get; set; }
        public string SAPLastPendingReason { get; set; }
        public Nullable<int> SubSiteId { get; set; }
        public int Membership { get; set; }
        public Nullable<System.DateTime> CertificateIssueDate { get; set; }
        public Nullable<short> RosterFrom { get; set; }
        public Nullable<float> Optionalcredithours1 { get; set; }
        public Nullable<int> SAPSyncCount { get; set; }
        public Nullable<System.DateTime> LastTimeSAPSync { get; set; }
        public Nullable<int> MetPrerequisite { get; set; }
        public string CheckoutComments2 { get; set; }
        public Nullable<int> CourseSurveySent { get; set; }
        public Nullable<int> CRPartialPaymentMade { get; set; }
        public Nullable<float> CRPrimaryTotalPaid { get; set; }
        public string CRPartialPaymentPaidMethod { get; set; }
        public Nullable<float> CRPartialPaymentPaidAmount { get; set; }
        public string CRPartialPaymentPaidNote { get; set; }
        public Nullable<int> BBCancelled { get; set; }
        public Nullable<System.DateTime> bb_graded_date { get; set; }
        public string bb_sent_cert { get; set; }
        public Nullable<int> viewpastcoursesdays { get; set; }
        public Nullable<decimal> creditcardfee { get; set; }
        public string CRPartialPaymentList { get; set; }
        public Nullable<float> paidremainderamount { get; set; }
        public string bb_sent_confirm { get; set; }
        public string survey_sent_confirm { get; set; }
        public Nullable<int> eventid { get; set; }
        public Nullable<System.DateTime> attendancedate { get; set; }
        public Nullable<int> HasPartialPayment { get; set; }
        public string bbautoenrollstatus { get; set; }
        public string internalnote { get; set; }
        public string regshipaddress { get; set; }
        public string regshipcity { get; set; }
        public string regshipstate { get; set; }
        public string regshipzip { get; set; }
        public Nullable<decimal> shippingfee { get; set; }
        public string shippingmethod { get; set; }
        public Nullable<System.DateTime> date_grade_notification { get; set; }
        public string regshipcountry { get; set; }
        public Nullable<System.DateTime> datepostauth { get; set; }
        public Nullable<System.DateTime> date_attendance_notified { get; set; }
        public Nullable<System.DateTime> date_transcript_notified { get; set; }
        public Nullable<System.DateTime> heliuslms_date_integrated { get; set; }
        public string preAuthAmount { get; set; }
        public Nullable<int> FTCourseRosterId { get; set; }
        public Nullable<int> StudentChoiceCourse { get; set; }
        public string SignInNotes { get; set; }
        public Nullable<System.DateTime> Reminder3Sent { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string CustomSignInNotes { get; set; }
        public string g2w_registrant_key { get; set; }
        public string g2w_join_url { get; set; }
        public Nullable<System.DateTime> g2w_attendance_date { get; set; }
        public string g2w_timein_webinar { get; set; }
        public Nullable<int> IsHoursPaid { get; set; }
        public Nullable<double> Optionalcredithours2 { get; set; }
        public Nullable<double> Optionalcredithours3 { get; set; }
        public Nullable<double> Optionalcredithours4 { get; set; }
        public Nullable<double> Optionalcredithours5 { get; set; }
        public Nullable<double> Optionalcredithours6 { get; set; }
        public Nullable<double> Optionalcredithours7 { get; set; }
        public Nullable<double> Optionalcredithours8 { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<int> Expire { get; set; }
        public string subscriptionId { get; set; }
        public string enrollmentnote { get; set; }
        public string bb_date_sync_instructor { get; set; }
        public string SingleRosterDiscountCoupon { get; set; }
        public Nullable<double> SingleRosterDiscountAmount { get; set; }
        public Nullable<int> haiku_roster_id { get; set; }
        public Nullable<int> sendSurvey { get; set; }
        public Nullable<Int32> canvas_roster_id { get; set; }
        public string blackboard_dsk { get; set; }
        public Nullable<int> ManualSentCertID { get; set; }
        public string EnrollToWaitListConfig { get; set; }
        public Nullable<int> canvas_skip { get; set; }
        public string clubpilatespackageinstallmentdetails { get; set; }
        public string blackboard_roster_id { get; set; }

        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual Course Cours { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<rostermaterial> rostermaterials { get; set; }
        public virtual ICollection<CourseExtraParticipant> CourseExtraParticipants { get; set; }
    }
}
