//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Attendances = new HashSet<Attendance>();
            this.AttendanceDetails = new HashSet<AttendanceDetail>();
            this.Course_Roster = new HashSet<Course_Roster>();
            this.Course_Times = new HashSet<Course_Time>();
            this.CourseExpenses = new HashSet<CourseExpense>();
            this.CourseOutlines = new HashSet<CourseOutline>();
            this.CoursePricingOptions = new HashSet<CoursePricingOption>();
            this.CoursesPendingRequests = new HashSet<CoursesPendingRequest>();
            this.CoursesRequirements = new HashSet<CoursesRequirement>();
            this.Transcripts = new HashSet<Transcript>();
            this.CourseChoices = new HashSet<CourseChoice>();
            this.FastTrackCourses = new HashSet<FastTrackCours>();
            this.FastTrackCourses1 = new HashSet<FastTrackCours>();
            this.MainCategories = new HashSet<MainCategory>();
        }
    
        public int COURSEID { get; set; }
        public string COURSENUM { get; set; }
        public string COURSENAME { get; set; }
        public Nullable<decimal> DISTPRICE { get; set; }
        public Nullable<decimal> NODISTPRICE { get; set; }
        public string LOCATION { get; set; }
        public string LOCATIONURL { get; set; }
        public string STREET { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string ROOM { get; set; }
        public Nullable<System.DateTime> TIMES { get; set; }
        public Nullable<int> MAXENROLL { get; set; }
        public Nullable<int> MAXWAIT { get; set; }
        public Nullable<int> INSTRUCTORID { get; set; }
        public Nullable<int> INSTRUCTORID2 { get; set; }
        public Nullable<int> INSTRUCTORID3 { get; set; }
        public string DESCRIPTION { get; set; }
        public string MAINCATEGORY { get; set; }
        public string MAINCATEGORY2 { get; set; }
        public string MAINCATEGORY3 { get; set; }
        public string SUBCATEGORY1 { get; set; }
        public string SUBCATEGORY2 { get; set; }
        public string SUBCATEGORY1b { get; set; }
        public string SUBCATEGORY2b { get; set; }
        public string SUBCATEGORY1c { get; set; }
        public string SUBCATEGORY2c { get; set; }
        public string MATERIALS { get; set; }
        public Nullable<int> DAYS { get; set; }
        public Nullable<double> CREDITHOURS { get; set; }
        public Nullable<byte> SubStatus { get; set; }
        public string NUMSUBSAVAIL { get; set; }
        public string EVENTNUM { get; set; }
        public string ACCOUNTNUM { get; set; }
        public short CANCELCOURSE { get; set; }
        public Nullable<int> EmailReminderType { get; set; }
        public string EmailReminderSubject { get; set; }
        public string EmailReminderBody { get; set; }
        public string Notes { get; set; }
        public short InternalClass { get; set; }
        public string PriceTypes { get; set; }
        public string nonPriceTypes { get; set; }
        public short DisplayPrice { get; set; }
        public Nullable<short> MaterialsRequired { get; set; }
        public Nullable<int> Audience { get; set; }
        public int AudienceID { get; set; }
        public short GradingSystem { get; set; }
        public short BuybackCourse { get; set; }
        public int DepartmentNameID { get; set; }
        public string StartEndTimeDisplay { get; set; }
        public double InserviceHours { get; set; }
        public string Icons { get; set; }
        public string LinkTitle { get; set; }
        public string LinkURL { get; set; }
        public string ExcludedOptions { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public Nullable<int> CourseColorGrouping { get; set; }
        public string Special1 { get; set; }
        public string CourseCommentText { get; set; }
        public int courseoutlineid { get; set; }
        public int ShowTopCatalog { get; set; }
        public int ShowBoldCatalog { get; set; }
        public short AllowCreditRollover { get; set; }
        public Nullable<double> CustomCreditHours { get; set; }
        public Nullable<double> CEUCredit { get; set; }
        public Nullable<double> GraduateCredit { get; set; }
        public short Requirements { get; set; }
        public Nullable<int> OnlineCourse { get; set; }
        public string CustomCourseField1 { get; set; }
        public string CustomCourseField2 { get; set; }
        public Nullable<int> HalfDayCourse { get; set; }
        public Nullable<decimal> SpecialDistPrice1 { get; set; }
        public int Duplicated { get; set; }
        public Nullable<System.DateTime> WaitListJobDate { get; set; }
        public Nullable<int> SubSiteId { get; set; }
        public string ExternalKey { get; set; }
        public string SubSiteCourseImportKey { get; set; }
        public string CourseConfirmationEmailExtraText { get; set; }
        public Nullable<short> ShowCreditRequirementLink { get; set; }
        public Nullable<int> CourseCloseDays { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public Nullable<int> Percent4MultiEnrollDiscount { get; set; }
        public Nullable<int> MinStudentNum4MultiEnrollDiscount { get; set; }
        public string CustomCourseField3 { get; set; }
        public string CustomCourseField4 { get; set; }
        public string LocationAdditionalInfo { get; set; }
        public Nullable<int> RoomDirectionsId { get; set; }
        public Nullable<int> CoursesType { get; set; }
        public Nullable<int> CollectExtraParticipant { get; set; }
        public string courseinternalaccesscode { get; set; }
        public string CourseStudentInfoRequired { get; set; }
        public string OfflineStudentNames { get; set; }
        public Nullable<int> Membership { get; set; }
        public int OfflineStudentCount { get; set; }
        public string LDAPGroupMatch { get; set; }
        public string ElectronicSignatureFile { get; set; }
        public string ElectronicSignatureFile2 { get; set; }
        public string ElectronicSignatureFile3 { get; set; }
        public string CourseTypeAltVerbiage { get; set; }
        public Nullable<int> BBCourseCloned { get; set; }
        public Nullable<int> CoursesHideFromCatalog { get; set; }
        public Nullable<float> Optionalcredithours1 { get; set; }
        public Nullable<int> ShowPrerequisite { get; set; }
        public string PrerequisiteInfo { get; set; }
        public Nullable<int> RemindInstructor { get; set; }
        public string bb_last_integration_state { get; set; }
        public Nullable<System.DateTime> bb_last_integration_date { get; set; }
        public Nullable<System.DateTime> bb_last_update_grade { get; set; }
        public Nullable<int> coursecertificate { get; set; }
        public Nullable<int> CourseSpecificEnrollmentCheck { get; set; }
        public Nullable<int> viewpastcoursesdays { get; set; }
        public string ShortDescription { get; set; }
        public Nullable<short> SpecialCourseType { get; set; }
        public string CustomCourseField5 { get; set; }
        public string CustomCourseField6 { get; set; }
        public Nullable<int> mandatory { get; set; }
        public Nullable<int> freeclass { get; set; }
        public Nullable<int> NoRegEmail { get; set; }
        public Nullable<int> useRoommateMatch { get; set; }
        public Nullable<int> coursetype { get; set; }
        public Nullable<int> eventid { get; set; }
        public Nullable<int> sessionid { get; set; }
        public Nullable<int> BBServer { get; set; }
        public Nullable<int> bbautoenroll { get; set; }
        public Nullable<int> forimportonly { get; set; }
        public string Country { get; set; }
        public string PartialPaymentAmount { get; set; }
        public string PartialPaymentSP { get; set; }
        public string PartialPaymentNon { get; set; }
        public Nullable<System.DateTime> heliuslms_last_integration { get; set; }
        public Nullable<int> heliuslmscloned { get; set; }
        public Nullable<int> archived_course { get; set; }
        public string google_calendar { get; set; }
        public Nullable<int> google_calendar_import_enable { get; set; }
        public Nullable<int> StudentChoiceCourse { get; set; }
        public Nullable<int> CourseCertificationsId { get; set; }
        public Nullable<int> SendConfirmationEmailtoInstructor { get; set; }
        public string attendanceThreshold { get; set; }
        public Nullable<int> MinMultiEnrolDiscountAll { get; set; }
        public string Amount4MultiEnrollDiscount { get; set; }
        public Nullable<decimal> SingleCreditCost { get; set; }
        public Nullable<double> Optionalcredithours2 { get; set; }
        public Nullable<double> Optionalcredithours3 { get; set; }
        public Nullable<double> Optionalcredithours4 { get; set; }
        public Nullable<double> Optionalcredithours5 { get; set; }
        public Nullable<double> Optionalcredithours6 { get; set; }
        public Nullable<double> Optionalcredithours7 { get; set; }
        public Nullable<double> Optionalcredithours8 { get; set; }
        public string CustomDropDownValueSequence { get; set; }
        public Nullable<int> showcreditinpublic { get; set; }
        public Nullable<int> AllowSendSurvey { get; set; }
        public string TileImageUrl { get; set; }
        public Nullable<int> haiku_course_id { get; set; }
        public string haiku_import_id { get; set; }
        public Nullable<System.DateTime> haiku_integration_date { get; set; }
        public Nullable<System.DateTime> haiku_last_integration_date { get; set; }
        public string haiku_last_result { get; set; }
        public Nullable<int> disablehaikuintegration { get; set; }
        public Nullable<int> disable_canvas_integration { get; set; }
        public Nullable<int> canvas_course_id { get; set; }
        public string bb_date_sync_instructor { get; set; }
        public string blackboard_dsk { get; set; }
        public string CourseConfiguration { get; set; }
        public Nullable<int> clubready_package_id { get; set; }
         public string blackboard_api_uuid { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual ICollection<AttendanceDetail> AttendanceDetails { get; set; }
        public virtual ICollection<Course_Roster> Course_Roster { get; set; }
        public virtual ICollection<Course_Time> Course_Times { get; set; }
        public virtual ICollection<CourseExpense> CourseExpenses { get; set; }
        public virtual ICollection<CourseOutline> CourseOutlines { get; set; }
        public virtual ICollection<CoursePricingOption> CoursePricingOptions { get; set; }
        public virtual ICollection<CoursesPendingRequest> CoursesPendingRequests { get; set; }
        public virtual ICollection<CoursesRequirement> CoursesRequirements { get; set; }
        public virtual ICollection<Transcript> Transcripts { get; set; }
        public virtual ICollection<CourseChoice> CourseChoices { get; set; }
        public virtual ICollection<FastTrackCours> FastTrackCourses { get; set; }
        public virtual ICollection<FastTrackCours> FastTrackCourses1 { get; set; }
        public virtual ICollection<MainCategory> MainCategories { get; set; }
    }
}
