//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesRequirement
    {
        public int CoursesRequirementsID { get; set; }
        public int CourseID { get; set; }
        public Nullable<short> SchoolID { get; set; }
        public Nullable<short> GradeLevelID { get; set; }
        public Nullable<short> Position { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
