//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseExpense
    {
        public int CourseExpenseId { get; set; }
        public string CourseExpenseTitle { get; set; }
        public Nullable<decimal> CourseExpenseAmount { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> InstructorId { get; set; }
        public Nullable<decimal> InstructorFixedFee { get; set; }
        public Nullable<decimal> InstructorPerStudent { get; set; }
        public Nullable<float> InstructorRevenuePercentage { get; set; }
        public int InstructorDisplayPosition { get; set; }
        public Nullable<int> CourseDisplayPosition { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
