//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesPendingRequest
    {
        public int CoursesPendingRequestsId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string RequestorName { get; set; }
        public string RequestorEmail { get; set; }
        public string RequestDescription { get; set; }
        public string RequestorCompany { get; set; }
        public Nullable<int> RequestMainCategoryId { get; set; }
        public Nullable<int> RequestSubCategoryId { get; set; }
        public string RequestCourseNum { get; set; }
        public string RequestCourseTitle { get; set; }
        public Nullable<int> RequestInstructorId { get; set; }
        public Nullable<int> RequestNumberOfDays { get; set; }
        public Nullable<int> RequestSeatsAvail { get; set; }
        public Nullable<int> RequestWLSeatsAvail { get; set; }
        public Nullable<float> RequestCourseHours { get; set; }
        public Nullable<decimal> RequestCoursePrice { get; set; }
        public Nullable<int> RequestLocationId { get; set; }
        public string RequestAddInfo { get; set; }
        public string RequestCourseDatesTimes { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string RequestMainCategory { get; set; }
        public string RequestSubCategory { get; set; }
        public string RequestInstructor { get; set; }
        public string RequestLocation { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
