//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursePricingOption
    {
        public int CoursePricingOptionId { get; set; }
        public decimal Price { get; set; }
        public int Type { get; set; }
        public int CourseId { get; set; }
        public int PricingOptionId { get; set; }
        public Nullable<int> rangestart { get; set; }
        public Nullable<int> rangeend { get; set; }
        public string PriceTypedesc { get; set; }
        public Nullable<int> SubscriptionLength { get; set; }
    
        public virtual Course Cours { get; set; }
    }
}
