//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customcetificate
    {
        public int customcertid { get; set; }
        public string certtitle { get; set; }
        public Nullable<int> certheight { get; set; }
        public Nullable<int> certwidth { get; set; }
        public Nullable<int> marginTop { get; set; }
        public Nullable<int> marginBottom { get; set; }
        public Nullable<int> marginLeft { get; set; }
        public Nullable<int> marginRight { get; set; }
        public Nullable<int> boundX { get; set; }
        public Nullable<int> boundY { get; set; }
        public string backgroundimage { get; set; }
        public string locheader1 { get; set; }
        public Nullable<int> useHeader1 { get; set; }
        public Nullable<int> fontsizeHeader1 { get; set; }
        public string locheader2 { get; set; }
        public Nullable<int> useHeader2 { get; set; }
        public Nullable<int> fontsizeHeader2 { get; set; }
        public string textInfo1 { get; set; }
        public string locinfo1 { get; set; }
        public Nullable<int> useInfo1 { get; set; }
        public Nullable<int> fontsizeInfo1 { get; set; }
        public string textInfo2 { get; set; }
        public string locinfo2 { get; set; }
        public Nullable<int> useInfo2 { get; set; }
        public Nullable<int> fontsizeInfo2 { get; set; }
        public string locname1 { get; set; }
        public string locname2 { get; set; }
        public string textCourseinfo1 { get; set; }
        public string loccourseinfo1 { get; set; }
        public Nullable<int> useCInfo1 { get; set; }
        public Nullable<int> fontsizeCInfo1 { get; set; }
        public string loccourseinfo2 { get; set; }
        public Nullable<int> useCInfo2 { get; set; }
        public Nullable<int> fontsizeCInfo2 { get; set; }
        public string loccoursedate1 { get; set; }
        public string loccoursedate2 { get; set; }
        public string locInstructor { get; set; }
        public Nullable<int> useInstructor { get; set; }
        public Nullable<int> fontsizeInstructor { get; set; }
        public string locsig1 { get; set; }
        public Nullable<int> useSig1 { get; set; }
        public string locsig2 { get; set; }
        public Nullable<int> useSig2 { get; set; }
        public string locfooter { get; set; }
        public Nullable<int> useFooter { get; set; }
        public string codefile { get; set; }
        public Nullable<int> useUploadedLogo { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<int> disabled { get; set; }
        public Nullable<int> useCourseNum { get; set; }
        public Nullable<int> useLocation { get; set; }
        public Nullable<int> subsiteid { get; set; }
        public Nullable<int> defaultcert { get; set; }
        public string locstudfield1 { get; set; }
        public Nullable<int> fontsizestudfield1 { get; set; }
        public Nullable<int> usestudfield1 { get; set; }
        public string locstudfield2 { get; set; }
        public Nullable<int> fontsizestudfield2 { get; set; }
        public Nullable<int> usestudfield2 { get; set; }
        public Nullable<int> fontsizestudfield3 { get; set; }
        public string locstudfield3 { get; set; }
        public Nullable<int> usestudfield3 { get; set; }
        public Nullable<int> usecredits { get; set; }
        public Nullable<int> fontsizecredits { get; set; }
        public string loccredits { get; set; }
        public Nullable<int> fontsizecourseloc { get; set; }
        public string loccourseloc { get; set; }
        public Nullable<int> usecourseloc { get; set; }
        public string loccoursenumber { get; set; }
        public Nullable<int> usecoursenumber { get; set; }
        public Nullable<int> fontsizecoursenumber { get; set; }
        public Nullable<int> usecourseicon { get; set; }
        public string loccourseicon { get; set; }
        public Nullable<int> fontsizecourseicon { get; set; }
        public string selectedstudfield1 { get; set; }
        public string selectedstudfield2 { get; set; }
        public string selectedstudfield3 { get; set; }
        public Nullable<int> usecoursedesc { get; set; }
        public string loccoursedesc { get; set; }
        public Nullable<int> fontsizecoursedesc { get; set; }
        public Nullable<int> usecoursedate { get; set; }
        public Nullable<int> fontsizecoursedate { get; set; }
        public Nullable<int> useCourseDuration { get; set; }
        public Nullable<int> fontsizestudname { get; set; }
        public Nullable<int> useExtraName { get; set; }
        public Nullable<int> showcoursetime { get; set; }
        public Nullable<int> showcourseenddate { get; set; }
        public Nullable<int> useLicense { get; set; }
        public Nullable<int> fontsizelicense { get; set; }
        public string loccourselicense { get; set; }
        public Nullable<int> surveyusecompdate { get; set; }
        public Nullable<int> uselicnumber { get; set; }
        public Nullable<int> fontsizelicnumber { get; set; }
        public string loclicnumber { get; set; }
        public Nullable<int> alignsname { get; set; }
        public Nullable<int> useDatePrint { get; set; }
        public string locDatePrint { get; set; }
        public Nullable<int> fontsizeDateprint { get; set; }
        public Nullable<int> showcourseenddateonly { get; set; }
        public Nullable<int> signatureDisplay { get; set; }
        public string loccustomcredit1 { get; set; }
        public string usecustomcredit { get; set; }
        public Nullable<int> usestudentid { get; set; }
        public string locstudentid { get; set; }
        public Nullable<int> fontsizestudid { get; set; }
        public Nullable<int> useStudentAddress { get; set; }
        public string locStudentAddress { get; set; }
        public Nullable<int> fontsizeStudentAddress { get; set; }
        public string startdateSettings { get; set; }
        public string enddateSettings { get; set; }
        public string daterangeSettings { get; set; }
        public string datelistSettings { get; set; }
        public string credithoursSettings { get; set; }
        public string inservicehoursSettings { get; set; }
        public string customcredittypeSettings { get; set; }
        public string ceucreditSettings { get; set; }
        public string graduatecreditSettings { get; set; }
        public string customtextSettings { get; set; }
        public string rosterdateaddedSettings { get; set; }
        public string studentnameSettings { get; set; }
        public string coursenameSettings { get; set; }
        public string courseaddtextSettings { get; set; }
        public string optionaltext1Settings { get; set; }
        public string optionaltext2Settings { get; set; }
        public string CustomCourseField1Settings { get; set; }
        public string CustomCourseField2Settings { get; set; }
        public string CustomCourseField3Settings { get; set; }
        public string CustomCourseField4Settings { get; set; }
        public string CustomCourseField5Settings { get; set; }
        public string customcredtisettings { get; set; }
        public string miscglobalsettings { get; set; }
        public string StudCustomField2Settings { get; set; }
        public string StudCustomField1Settings { get; set; }
        public string StudCustomField3Settings { get; set; }
    }
}
