//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class customtranscript
    {
        public int customtranid { get; set; }
        public string transtitle { get; set; }
        public Nullable<int> transheight { get; set; }
        public Nullable<int> transwidth { get; set; }
        public Nullable<int> marginTop { get; set; }
        public Nullable<int> marginBottom { get; set; }
        public Nullable<int> marginLeft { get; set; }
        public Nullable<int> marginRight { get; set; }
        public Nullable<int> boundX { get; set; }
        public Nullable<int> boundY { get; set; }
        public string backgroundimage { get; set; }
        public Nullable<int> useHeader1 { get; set; }
        public string locheader1 { get; set; }
        public Nullable<int> fontsizeHeader1 { get; set; }
        public Nullable<int> useInfo1 { get; set; }
        public string textInfo1 { get; set; }
        public string locinfo1 { get; set; }
        public Nullable<int> fontsizeInfo1 { get; set; }
        public Nullable<int> alignInfo1 { get; set; }
        public string locname1 { get; set; }
        public Nullable<int> alignsname1 { get; set; }
        public Nullable<int> fontsizename1 { get; set; }
        public Nullable<int> useAddress1 { get; set; }
        public string locaddress1 { get; set; }
        public Nullable<int> fontsizeAddress1 { get; set; }
        public Nullable<int> useStudField1 { get; set; }
        public string locStudField1 { get; set; }
        public Nullable<int> fontsizeStudfield1 { get; set; }
        public string selectedstudfield1 { get; set; }
        public Nullable<int> useStudField2 { get; set; }
        public string locStudField2 { get; set; }
        public Nullable<int> fontsizeStudfield2 { get; set; }
        public string selectedstudfield2 { get; set; }
        public Nullable<int> useStudField3 { get; set; }
        public string locStudField3 { get; set; }
        public Nullable<int> fontsizeStudfield3 { get; set; }
        public string selectedstudfield3 { get; set; }
        public Nullable<int> useCourseName { get; set; }
        public string locCoursename { get; set; }
        public Nullable<int> fontsizeCoursename { get; set; }
        public Nullable<int> includeCourseNum { get; set; }
        public Nullable<int> subsiteid { get; set; }
        public Nullable<int> disabled { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public Nullable<int> useDatePrint { get; set; }
        public string locDatePrint { get; set; }
        public Nullable<int> fontsizeDateprint { get; set; }
        public Nullable<int> usecourseloc { get; set; }
        public string loccourseloc { get; set; }
        public Nullable<int> fontsizecourseloc { get; set; }
        public Nullable<int> aligncloc { get; set; }
        public Nullable<int> customprofile { get; set; }
        public Nullable<int> alignstudfield1 { get; set; }
        public Nullable<int> alignstudfield2 { get; set; }
        public Nullable<int> alignstudfield3 { get; set; }
        public string coursenumbersettings { get; set; }
        public string instructorsetting { get; set; }
        public string coursedatesettings { get; set; }
        public string eventnumbersettings { get; set; }
        public string creditsettings { get; set; }
        public string totalcreditsettings { get; set; }
        public string customfieldsettings { get; set; }
        public string startdatesettings { get; set; }
        public string enddatesettings { get; set; }
        public Nullable<int> isdefaultselected { get; set; }
        public string selectedcoursefieldsettings { get; set; }
        public string coursefieldjsonsettings { get; set; }
        public string OptionalHeaderText { get; set; }
        public string CustomTranscriptEmailSubject { get; set; }
        public string CustomTranscriptEmailBody { get; set; }
        public string StudCustomField2Settings { get; set; }
        public string StudCustomField1Settings { get; set; }
        public string StudCustomField3Settings { get; set; }
        public Nullable<int> aligndateprinted { get; set; }
        public string coursegridconfiguration { get; set; }
    }
}
