//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.DistrictExtraInfoes = new HashSet<DistrictExtraInfo>();
        }
    
        public int DISTID { get; set; }
        public string DISTRICT1 { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> NoTaxShipping { get; set; }
        public Nullable<int> ShowAlternateConfirmation { get; set; }
        public Nullable<int> AltEmailConfirmation { get; set; }
        public Nullable<int> MembershipFlag { get; set; }
        public int HideInPublicArea { get; set; }
    
        public virtual ICollection<DistrictExtraInfo> DistrictExtraInfoes { get; set; }
    }
}
