//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistrictExtraInfo
    {
        public int dexid { get; set; }
        public string shortdesc { get; set; }
        public string daddress { get; set; }
        public string dcity { get; set; }
        public string dstate { get; set; }
        public string dzip { get; set; }
        public string dphone { get; set; }
        public string dfax { get; set; }
        public Nullable<int> districtID { get; set; }
        public string dcountry { get; set; }
    
        public virtual District District { get; set; }
    }
}
