//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailList
    {
        public int listid { get; set; }
        public string TemplateName { get; set; }
        public string cQuery { get; set; }
        public string cAttachment { get; set; }
        public string cSubject { get; set; }
        public string cBody { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string cResult { get; set; }
    }
}
