//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailQueue
    {
        public int eqID { get; set; }
        public string eqBCC { get; set; }
        public string eqto { get; set; }
        public string eqfrom { get; set; }
        public string eqbody { get; set; }
        public string eqRequestBy { get; set; }
        public string eqsubject { get; set; }
        public string eqAttachment { get; set; }
        public string eqRequestByUser { get; set; }
        public Nullable<System.DateTime> eqRequestDate { get; set; }
        public string eqRequestQuery { get; set; }
        public Nullable<System.DateTime> eqSendDate { get; set; }
        public Nullable<int> eqSendStatus { get; set; }
    }
}
