//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FastTrackCours
    {
        public int FastTrackCoursesId { get; set; }
        public int FTMainCourseId { get; set; }
        public int FTCourseId { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual Course Cours1 { get; set; }
    }
}
