//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldSpec
    {
        public int FieldSpecsId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public int FieldReadOnly { get; set; }
        public int FieldVisible { get; set; }
        public int FieldRequired { get; set; }
        public int FieldDisplaySortOrder { get; set; }
        public string FieldLabel { get; set; }
        public int YesNo { get; set; }
        public int Size { get; set; }
        public int MaxLength { get; set; }
        public int SystemConfigDisplayOrder { get; set; }
        public Nullable<int> ConfirmRequired { get; set; }
        public Nullable<int> FieldCertificationsId { get; set; }
        public Nullable<int> FieldListType { get; set; }
        public string FieldListValue { get; set; }
        public Nullable<int> ShowinMultipleEnroll { get; set; }
        public string GroupWidget { get; set; }
        public string shibboleth_attribute { get; set; }
    }
}
