//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMask
    {
        public int FieldMasksId { get; set; }
        public string TableName { get; set; }
        public string FieldName { get; set; }
        public int DefaultMaskNumber { get; set; }
        public string Mask1 { get; set; }
        public string Mask2 { get; set; }
        public string Mask3 { get; set; }
        public string Mask4 { get; set; }
        public Nullable<int> DistId { get; set; }
        public Nullable<int> PayId { get; set; }
        public string Mask5 { get; set; }
        public string Mask6 { get; set; }
        public string Mask7 { get; set; }
        public string Mask8 { get; set; }
        public string Mask9 { get; set; }
        public string Mask10 { get; set; }
    }
}
