//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Level
    {
        public Grade_Level()
        {
            this.GradeExtraInfoes = new HashSet<GradeExtraInfo>();
        }
    
        public int GRADEID { get; set; }
        public string GRADE { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> SchoolId { get; set; }
    
        public virtual ICollection<GradeExtraInfo> GradeExtraInfoes { get; set; }
    }
}
