//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int INSTRUCTORID { get; set; }
        public string INSTRUCTORNUM { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string SSN { get; set; }
        public string GRADELEVEL { get; set; }
        public Nullable<int> SCHOOL { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public short CLASSIFIED { get; set; }
        public short CERTIFIED { get; set; }
        public short OTHER { get; set; }
        public string CONTENT { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string HOMEPHONE { get; set; }
        public string WORKPHONE { get; set; }
        public string FAX { get; set; }
        public string EXPERIENCE { get; set; }
        public short DISTEMPLOYEE { get; set; }
        public short DISABLED { get; set; }
        public string Bio { get; set; }
        public string PhotoImage { get; set; }
        public string AdminNotes { get; set; }
        public string InstructorRegField1 { get; set; }
        public string InstructorRegField2 { get; set; }
        public string InstructorRegField3 { get; set; }
        public string InstructorRegField4 { get; set; }
        public string InstructorRegField5 { get; set; }
        public string InstructorRegField6 { get; set; }
        public string InstructorRegField7 { get; set; }
        public string InstructorRegField8 { get; set; }
        public string InstructorRegField9 { get; set; }
        public string InstructorRegField10 { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<System.DateTime> date_bb_integrated { get; set; }
        public string TempProfileImage { get; set; }
        public int haiku_user_id { get; set; }
        public string haiku_import_id { get; set; }
        public string lti_user_id { get; set; }
        public Nullable<long> canvas_user_id { get; set; }
        public string blackboard_dsk { get; set; }
        public string resetPasswordHash { get; set; }
        public Nullable<System.DateTime> resetPasswordDate { get; set; }
        public Nullable<System.Guid> UserSessionId { get; set; }

        public string Blackboard_user_UUID { get; set; }
    }
}
