//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainCategory
    {
        public MainCategory()
        {
            this.SubCategories = new HashSet<SubCategory>();
            this.SubSubCategories = new HashSet<SubSubCategory>();
        }
    
        public int MainCategoryID { get; set; }
        public string MainCategory1 { get; set; }
        public int CourseID { get; set; }
        public short MainOrder { get; set; }
        public int ShowTopCatalog { get; set; }
        public int ShowBoldCatalog { get; set; }
        public Nullable<short> SpecialCategoryType { get; set; }
        public Nullable<int> mcatorder { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual ICollection<SubCategory> SubCategories { get; set; }
        public virtual ICollection<SubSubCategory> SubSubCategories { get; set; }
    }
}
