//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public int AUTOINDEX { get; set; }
        public string MANAGERID { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public short DISABLED { get; set; }
        public string SecurityMatrix { get; set; }
        public int InstructorId { get; set; }
        public string PortalSettings { get; set; }
        public string WidgetSettings { get; set; }
        public string accessbuildingpermission { get; set; }
        public Nullable<System.Guid> UserSessionId { get; set; }
    }
}
