//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class masterinfo4
    {
        public int masterinfo4id { get; set; }
        public string ExtraParticipantLabel { get; set; }
        public Nullable<int> subsiteid { get; set; }
        public string PublicHeaderContent { get; set; }
        public string PublicFooterContent { get; set; }
        public string PublicWelcomeMessageContent { get; set; }
        public Nullable<int> PublicHeaderVisible { get; set; }
        public Nullable<int> PublicFooterVisible { get; set; }
        public Nullable<int> PublicWelcomeMessageVisible { get; set; }
        public string PublicButtonLabelAddToCart { get; set; }
        public string PublicButtonLabelCheckout { get; set; }
        public string PublicButtonLabelEnrolled { get; set; }
        public string MultipleSignUpCustomText { get; set; }
        public Nullable<int> ShowAllMembershipPrice { get; set; }
        public string PublicCourseBrowserLayoutConfiguration { get; set; }
        public string LiteFeatures { get; set; }
        public string SubscriptionEmailSubject { get; set; }
        public string SubscriptionEmailBody { get; set; }
        public Nullable<int> SubscriptionSentBy { get; set; }
        public Nullable<int> LoginAuthOption { get; set; }
        public string google_sso_api_key { get; set; }
        public Nullable<int> google_drive_enabled { get; set; }
        public string OrbitalUsername { get; set; }
        public string OrbitalPassword { get; set; }
        public string OrbitalMerchantID { get; set; }
        public Nullable<int> OrbitalServer { get; set; }
        public Nullable<int> UseOrbital { get; set; }
        public Nullable<int> UseTouchnet { get; set; }
        public Nullable<int> touchnetsiteid { get; set; }
        public string TouchnetServer { get; set; }
        public Nullable<int> AllowCourseSubscription { get; set; }
        public Nullable<int> SecondSubscriptionSentBy { get; set; }
        public string PublicLayoutConfiguration { get; set; }
        public Nullable<int> SendRefundErrorEmails { get; set; }
        public Nullable<int> AllowCouponPerOrder { get; set; }
        public string AspSiteRootUrl { get; set; }
        public string DotNetSiteRootUrl { get; set; }
        public string currentVersion { get; set; }
        public string StudentsDashViewEdit { get; set; }
        public string StudentsDashAddnew { get; set; }
        public string InstructorsDashViewEdit { get; set; }
        public string InstructorsDashAddnew { get; set; }
        public string StudentsDashAdmin { get; set; }
        public string InstructorsDashAdmin { get; set; }
        public string EmailInstructorFullCancelSubject { get; set; }
        public string EmailInstructorFullCancelBody { get; set; }
        public Nullable<int> SendInstructorCancelEmails { get; set; }
        public string clientKey { get; set; }
        public string clientSecret { get; set; }
        public string HaikuConfiguration { get; set; }
        public Nullable<int> courseDisplayPriceDefault { get; set; }
        public Nullable<int> showCourseDateInConfEmail { get; set; }
        public string LtiConfiguration { get; set; }
        public Nullable<int> shibboleth_sso_enabled { get; set; }
        public Nullable<int> shibboleth_required_login { get; set; }
        public Nullable<int> public_course_listing_fast_load { get; set; }
        public string shibboleth_logout_link { get; set; }
        public string CanvasConfiguration { get; set; }
        public string SigninSheetConfiguration { get; set; }
        public string blackboard_students_dsk { get; set; }
        public string blackboard_courses_dsk { get; set; }
        public string blackboard_instructors_dsk { get; set; }
        public string blackboard_course_roster_dsk { get; set; }
        public string blackboard_students_node_id { get; set; }
        public string blackboard_courses_node_id { get; set; }
        public string blackboard_instructors_node_id { get; set; }
        public Nullable<int> DisplayNonDefaultMembership { get; set; }
        public Nullable<int> RubyUpdateLevel { get; set; }
        public Nullable<int> UseTouchnetTlink { get; set; }
        public string TouchnetTLinkServiceurl { get; set; }
        public string TouchnetTLinkUserName { get; set; }
        public string TouchnetTLinkPassword { get; set; }
        public Nullable<int> shibboleth_allow_gsmu_login { get; set; }
        public string SystemCharset { get; set; }
        public string HourPurchaseEmailSubject { get; set; }
        public string HourPurchaseEmailBody { get; set; }
        public Nullable<int> allow_quantity_purchase { get; set; }
        public string customcreditsettings { get; set; }
        public string customtranscript { get; set; }
        public string BlackboardConfiguration { get; set; }
        public string CASStudentIntegrationFields { get; set; }
        public string ChangeDateEmail { get; set; }
        public string ChangeDateSubject { get; set; }
        public Nullable<int> UseiPay { get; set; }
        public string iPayGatewayConfiguration { get; set; }
        public string CASAuthConfiguration { get; set; }
        public Nullable<int> supervisorrestrictschoolanddistrict { get; set; }
        public string SupervisorsDashAddnew { get; set; }
        public string SupervisorsDashViewEdit { get; set; }
        public string blackboard_security_key { get; set; }
        public string ShibbolethConfiguration { get; set; }
        public string InstructorConfiguration { get; set; }
        public Nullable<int> disable_blackboard_modifed { get; set; }
        public string SupervisorConfiguration { get; set; }
        public string GlobalConfiguration { get; set; }
        public string CashNetConfiguration { get; set; }
        public string ClubPilatesConfiguration { get; set; }
        public string MultipleEnrollment { get; set; }
        public string RevTrakConfiguration { get; set; }
        public string SpreedlyConfiguration { get; set; }
        public Nullable<int> CompleteSupAccountToSupervisor { get; set; }

        public string blackboard_api_url { get; set; }

        public Nullable<int> use_blackboard_api { get; set; }
        public string blackboard_access_token { get; set; }
        public Nullable<System.DateTime> blackboard_token_expiry { get; set; }
    }
}
