//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalInfo
    {
        public int OptionalInfoId { get; set; }
        public int MainCategoryId { get; set; }
        public int SubCategoryId { get; set; }
        public int OptionalInfo1 { get; set; }
        public int OptionalInfo2A { get; set; }
        public int OptionalInfo2B { get; set; }
        public int OptionalInfo2C { get; set; }
        public int OptionalInfo2D { get; set; }
        public int OptionalInfo2E { get; set; }
        public int OptionalInfo2F { get; set; }
        public int OptionalInfo2G { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
    }
}
