//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTransaction
    {
        public int OrderTransactionId { get; set; }
        public int RosterId { get; set; }
        public int OrderTransactionType { get; set; }
        public System.DateTime OrderTransactionDateTime { get; set; }
        public string OrderTransactionNotes { get; set; }
        public Nullable<decimal> OrderTransactionAmount { get; set; }
        public string OrderTransactionRefNumber { get; set; }
        public string OrderTransactionRespMsg { get; set; }
        public string OrderTransactionAuthNum { get; set; }
        public string OrderTransactionPaymentType { get; set; }
    }
}
