//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInProgress
    {
        public int OrderInProgressId { get; set; }
        public string OrderNumber { get; set; }
        public string OrderMethod { get; set; }
        public string OrderPrice { get; set; }
        public Nullable<System.DateTime> orderdate { get; set; }
        public string ordername { get; set; }
        public string ordercourses { get; set; }
        public string orderdetails { get; set; }
        public string coursedetails { get; set; }
        public string userlogindetails { get; set; }
        public string OrderCurStatus { get; set; }
        public string paymentdetails { get; set; }
        public string MasterOrderNumber { get; set; }
        public Nullable<System.DateTime> postbackdate { get; set; }
        public Nullable<System.Guid> UserSessionid { get; set; }
    }
}
