//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailView
    {
        public int RosterID { get; set; }
        public string CRPartialPaymentList { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> mincoursedate { get; set; }
        public Nullable<System.DateTime> maxcoursedate { get; set; }
        public Nullable<int> StudentChoiceCourse { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public string CourseChoice { get; set; }
        public Nullable<int> ShowChoiceCourse { get; set; }
        public string CreditAppliedA { get; set; }
        public string LAST { get; set; }
        public string FIRST { get; set; }
        public Nullable<int> eid { get; set; }
        public string @enum { get; set; }
        public string ename { get; set; }
        public Nullable<int> sid { get; set; }
        public string snum { get; set; }
        public string sname { get; set; }
        public string COURSENAME { get; set; }
        public string COURSENUM { get; set; }
        public string ACCOUNTNUM { get; set; }
        public Nullable<short> CANCELCOURSE { get; set; }
        public Nullable<int> CRCCAuditCount { get; set; }
        public string homephonelabel { get; set; }
        public string workphonelabel { get; set; }
        public string faxlabel { get; set; }
    }
}
