//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ParentsID { get; set; }
        public string ParentsFirstName { get; set; }
        public string ParentsLastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public Nullable<System.DateTime> PCSDate { get; set; }
        public int Inactive { get; set; }
        public string BranchOfService { get; set; }
        public string RankRateGrade { get; set; }
        public string CommandDepartment { get; set; }
        public string CellPhone { get; set; }
        public string SpouseName { get; set; }
        public string SpouseWorkPhone { get; set; }
        public string SpouseCellPhone { get; set; }
        public string SpouseEmail { get; set; }
        public string EmergencyName1 { get; set; }
        public string EmergencyHomePhone1 { get; set; }
        public string EmergencyWorkPhone1 { get; set; }
        public string EmergencyAddress1 { get; set; }
        public int EmergencyPOA1 { get; set; }
        public string EmergencyName2 { get; set; }
        public string EmergencyHomePhone2 { get; set; }
        public string EmergencyWorkPhone2 { get; set; }
        public string EmergencyAddress2 { get; set; }
        public int EmergencyPOA2 { get; set; }
        public int ParentLevelOneId { get; set; }
        public int ParentLevelTwoId { get; set; }
        public int ParentLevelThreeId { get; set; }
        public string Fax { get; set; }
        public string ParentRegField1 { get; set; }
        public string ParentRegField2 { get; set; }
        public string ParentRegField3 { get; set; }
        public string ParentRegField4 { get; set; }
        public string ParentRegField5 { get; set; }
        public string ParentRegField6 { get; set; }
        public string ParentRegField7 { get; set; }
        public string ParentRegField8 { get; set; }
        public string ParentRegField9 { get; set; }
        public string ParentRegField10 { get; set; }
        public string ReadOnlyParentRegField1 { get; set; }
        public string ReadOnlyParentRegField2 { get; set; }
        public string ReadOnlyParentRegField3 { get; set; }
        public string ReadOnlyParentRegField4 { get; set; }
        public string HiddenParentRegField1 { get; set; }
        public string HiddenParentRegField2 { get; set; }
        public string resetPasswordHash { get; set; }
        public Nullable<System.DateTime> resetPasswordDate { get; set; }
    }
}
