//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDFHeaderFooterInfo
    {
        public int ID { get; set; }
        public string Header1 { get; set; }
        public string Header2 { get; set; }
        public string Footer1 { get; set; }
        public string Footer2 { get; set; }
        public string Footer3 { get; set; }
        public string LogoImage { get; set; }
        public string LogoURL { get; set; }
        public string PDFLogoImage { get; set; }
        public string CertLogoImage { get; set; }
        public string HTMLDocLocation { get; set; }
        public Nullable<int> RosterLayout { get; set; }
        public Nullable<int> Forcelogin { get; set; }
        public string LogoPublic { get; set; }
        public Nullable<short> LogoRoomMgmt { get; set; }
        public string BuybackLabel { get; set; }
        public string BuybackImage { get; set; }
        public string CertSignature { get; set; }
        public string EditOrderFooter { get; set; }
        public string CertWatermarkImage { get; set; }
        public int HideHeader1 { get; set; }
        public int HideLogoImage { get; set; }
        public string HTMLTitle { get; set; }
        public string TitleIntro { get; set; }
        public short TitleHeight { get; set; }
        public string CatalogHeaderImage { get; set; }
        public string cartemptybuttonimage { get; set; }
        public string enrollbuttonimage { get; set; }
        public string signupbuttonimage { get; set; }
        public string signinsheetpdftitle { get; set; }
        public string signinsheetpdfmessage { get; set; }
        public string CalendarHeaderImage { get; set; }
        public Nullable<int> SubSiteId { get; set; }
        public string PublicLoginText { get; set; }
        public string SignUpImage { get; set; }
        public string CourseDetailSignUpImage { get; set; }
        public string LoginImage { get; set; }
        public string ForgotPasswordSubmitImage { get; set; }
        public string AdminAreaLogoImage { get; set; }
        public string CompanyName { get; set; }
        public string ConfirmHeader { get; set; }
        public string ConfirmFooter { get; set; }
        public string PublicFooterText { get; set; }
        public string GenericSubmitImage { get; set; }
        public string ProcessingImage { get; set; }
        public string signinsheetpdftitle2 { get; set; }
        public Nullable<int> HideHeader1OnTitle { get; set; }
        public string headerbggfx { get; set; }
        public string Catalogbggfx { get; set; }
        public string ConEventButtonImage { get; set; }
        public string SocialMediaLogo { get; set; }
        public string NewPDFLogoImage { get; set; }
    }
}
