//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportRequest
    {
        public int reportrequestid { get; set; }
        public string reporttitle { get; set; }
        public string reportname { get; set; }
        public int processid { get; set; }
        public System.DateTime timestarted { get; set; }
        public int timespent { get; set; }
        public int percentagecomplete { get; set; }
        public string requestorid { get; set; }
        public string reportfile { get; set; }
        public string reportparameters { get; set; }
        public string filename { get; set; }
        public System.DateTime insertdate { get; set; }
        public string ErrorMsg { get; set; }
        public string SQLStmt { get; set; }
    }
}
