//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewOrderView
    {
        public string OrderId { get; set; }
        public string LAST { get; set; }
        public string FIRST { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public string masterordernumber2 { get; set; }
        public Nullable<short> PartialWaiting { get; set; }
        public Nullable<int> WaitingStatus { get; set; }
        public string PAYMETHOD { get; set; }
        public string payNumber { get; set; }
        public Nullable<decimal> TotalRefund { get; set; }
        public Nullable<int> cancelled { get; set; }
        public Nullable<int> notcancelled { get; set; }
        public string Status { get; set; }
        public Nullable<int> C_subsiteID { get; set; }
        public Nullable<System.DateTime> LatestChargeDate { get; set; }
        public string RespMsg { get; set; }
        public string Result { get; set; }
        public string Customer { get; set; }
        public string payment_type { get; set; }
        public Nullable<double> mATERIALCOST { get; set; }
        public Nullable<float> CouponDiscount { get; set; }
        public Nullable<decimal> OrderTotal { get; set; }
        public Nullable<System.DateTime> DateRosterAdded { get; set; }
        public Nullable<decimal> RosterTotalPaid { get; set; }
        public Nullable<int> DISTRICT { get; set; }
        public Nullable<int> SCHOOL { get; set; }
        public Nullable<int> GRADE { get; set; }
        public string DISTRICTNAME { get; set; }
        public string SCHOOLNAME { get; set; }
        public string GRADENAME { get; set; }

        public string ACCOUNTNUM { get; set; }
        public string masterordertag { get; set; }
        public short Cancel { get; set; }
        public string CourseNameNumber { get; set; }
        public Nullable<decimal> CourseCost { get; set; }
        public Nullable<decimal> CourseSalesTaxPaid { get; set; }
        public Nullable<decimal> creditcardfee { get; set; }
        public Nullable<decimal> NonRefundableMatShipCost { get; set; }
        public Nullable<decimal> FinalMaterialCost { get; set; }
        public Nullable<decimal> FinalSubTotal { get; set; }
        public Nullable<decimal> FinalDiscount { get; set; }
        public Nullable<decimal> FinalDiscountedSubTotal { get; set; }
        public Nullable<decimal> FinalShippingCost { get; set; }
        public Nullable<decimal> FinalSalesTax { get; set; }
        public Nullable<decimal> FinalGrandTotal { get; set; }
        public Nullable<decimal> FinalTotalPaid { get; set; }
        public Nullable<decimal> FinalDueAmount { get; set; }
    }
}
