//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterCostMaterialGridComn
    {
        public Nullable<int> RosterID { get; set; }
        public Nullable<int> RsMatCount { get; set; }
        public double MaterialFee { get; set; }
        public Nullable<double> MaterialCost { get; set; }
        public Nullable<decimal> CoursePrice { get; set; }
        public Nullable<double> CourseTotal { get; set; }
        public Nullable<double> TxTotal { get; set; }
        public string MaterialNames { get; set; }
    }
}
