//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RosterReportView
    {
        public short cancelcourse { get; set; }
        public string CourseNameID { get; set; }
        public string CourseDateID { get; set; }
        public int courseid { get; set; }
        public string COURSENAME { get; set; }
        public string COURSENUM { get; set; }
        public string Location { get; set; }
        public short internalclass { get; set; }
        public Nullable<int> maxenroll { get; set; }
        public Nullable<int> maxwait { get; set; }
        public string room { get; set; }
        public Nullable<int> instructorid { get; set; }
        public Nullable<int> instructorid2 { get; set; }
        public Nullable<int> instructorid3 { get; set; }
        public string materials { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<double> credithours { get; set; }
        public Nullable<int> CourseCloseDays { get; set; }
        public string description { get; set; }
        public string maincategory { get; set; }
        public string subcategory { get; set; }
        public string subsubcategory { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public short WAITING { get; set; }
        public string internalnote { get; set; }
        public string enrollmentnote { get; set; }
        public string ordernum { get; set; }
        public string PAYMETHOD { get; set; }
        public string payNumber { get; set; }
        public string authnum { get; set; }
        public string refnumber { get; set; }
        public string CouponCode { get; set; }
        public Nullable<float> CouponDiscount { get; set; }
        public string CouponDetails { get; set; }
        public string StudentGrade { get; set; }
        public Nullable<decimal> course { get; set; }
        public short PAIDINFULL { get; set; }
        public Nullable<decimal> amountpaid { get; set; }
        public int RosterID { get; set; }
        public string creditapplied { get; set; }
        public short cancel { get; set; }
        public short Attended { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string crinitialauditinfo { get; set; }
        public string coursechoice { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string STATE { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string HOMEPHONE { get; set; }
        public string WORKPHONE { get; set; }
        public string FAX { get; set; }
        public string StudRegField1 { get; set; }
        public string studRegfield2 { get; set; }
        public string StudRegField3 { get; set; }
        public string studRegfield4 { get; set; }
        public string StudRegField5 { get; set; }
        public string studRegfield6 { get; set; }
        public string StudRegField7 { get; set; }
        public string studRegfield8 { get; set; }
        public string StudRegField9 { get; set; }
        public string studRegfield10 { get; set; }
        public string StudRegField11 { get; set; }
        public string studRegfield12 { get; set; }
        public string StudRegField13 { get; set; }
        public string studRegfield14 { get; set; }
        public string StudRegField15 { get; set; }
        public string studRegfield16 { get; set; }
        public string StudRegField17 { get; set; }
        public string studRegfield18 { get; set; }
        public string StudRegField19 { get; set; }
        public string studRegfield20 { get; set; }
        public string hiddenstudregfield1 { get; set; }
        public string hiddenstudregfield2 { get; set; }
        public string readonlystudregfield1 { get; set; }
        public string readonlystudregfield2 { get; set; }
        public string readonlystudregfield3 { get; set; }
        public string readonlystudregfield4 { get; set; }
        public string studentschool { get; set; }
        public string district { get; set; }
        public string studentgradelevel { get; set; }
        public string i1first { get; set; }
        public string i1last { get; set; }
        public string i2first { get; set; }
        public string i2last { get; set; }
        public string i3first { get; set; }
        public string i3last { get; set; }
        public string instructor { get; set; }
        public string instructor2 { get; set; }
        public string instructor3 { get; set; }
        public string cancelledtxt { get; set; }
        public string waitingtxt { get; set; }
        public string attendedtxt { get; set; }
        public string PaidFulltxt { get; set; }
        public Nullable<decimal> Credited { get; set; }
        public Nullable<int> RMCount { get; set; }
        public string materialnames { get; set; }
        public Nullable<double> Material { get; set; }
        public Nullable<double> CourseTotal { get; set; }
        public Nullable<double> TxTotal { get; set; }
        public string CompleteAddress { get; set; }
        public string CourseLocation { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string daddress { get; set; }
        public Nullable<long> Count { get; set; }
        public string additionalemail { get; set; }
        public string masterordernumber { get; set; }
        public string EnrollToWaitStatus { get; set; }
        public string EnrollToWaitListConfig { get; set; }
        public string Accountnum { get; set; }
        public string canvassectioncourse { get; set; }

        public string username { get; set; }
    }
}
