//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAPIntegration
    {
        public int SAPIntegrationId { get; set; }
        public Nullable<int> SAPIntegrationOn { get; set; }
        public string SAPIntegrationRelayURL { get; set; }
        public string SAPIntegrationWebServiceURL { get; set; }
        public Nullable<int> SAPIntegrationRelayPort { get; set; }
        public Nullable<int> SAPIntegrationWebServicePort { get; set; }
        public string SAPIntegrationPendingEmailSubject { get; set; }
        public string SAPIntegrationPendingEmailBody { get; set; }
        public string SAPIntegrationConfirmEmailSubject { get; set; }
        public string SAPIntegrationConfirmEmailBody { get; set; }
        public Nullable<System.DateTime> SAPIntegrationSAPIRanDate { get; set; }
        public int SAPIntegrationURLTimeOut { get; set; }
        public int SAPIntegrationTimeZoneDiff { get; set; }
        public string SAPIntegrationRegister_VerifyMethod { get; set; }
        public string SAPIntegrationMakeBookingMethod_VerifyMethod { get; set; }
        public string SAPIntegrationCancelBookingMethod_VerifyMethod { get; set; }
        public string SAPIntegrationWebServiceURL1 { get; set; }
        public string SAPIntegrationWebServiceURL2 { get; set; }
        public Nullable<System.DateTime> LastCommunicationDateTime { get; set; }
        public string SAPIntegrationNewRegisterEmailSubject { get; set; }
        public string SAPIntegrationNewRegisterEmailBody { get; set; }
        public string SAPIntegrationInquireMethod { get; set; }
        public string SAPIntegrationWebServiceURL3 { get; set; }
        public string SAPIntegrationPendingNewRegisterEmailSubject { get; set; }
        public string SAPIntegrationPendingNewRegisterEmailBody { get; set; }
        public int SAPIntegrationSendEmail { get; set; }
        public int SAPIntegrationSendNewRegisterEmail { get; set; }
        public int SAPIntegrationSendPendingEmail { get; set; }
        public int SAPIntegrationSendPendingNewRegisterEmail { get; set; }
        public int SAPIntegrationAutoPullCourseInfo { get; set; }
        public string SAPIntegrationNotFoundMessage { get; set; }
        public string SAPIntegrationESSURL { get; set; }
        public Nullable<System.DateTime> SAPIntegrationImportRanDate { get; set; }
        public int SAPIntegrationImportErrorCount { get; set; }
    }
}
