//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public int ID { get; set; }
        public Nullable<int> locationid { get; set; }
        public string LOCATION { get; set; }
        public string URL { get; set; }
        public Nullable<int> District { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> MembershipFlag { get; set; }
        public string LocationAlias { get; set; }
        public Nullable<int> certid { get; set; }
    
        public virtual Location Location1 { get; set; }
    }
}
