//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolExtraInfo
    {
        public int sexid { get; set; }
        public string schoolshortdesc { get; set; }
        public string sshipnumber { get; set; }
        public string saddress { get; set; }
        public string scity { get; set; }
        public string sstate { get; set; }
        public string szip { get; set; }
        public string sphonenum { get; set; }
        public string sfaxnum { get; set; }
        public Nullable<int> schoolid { get; set; }
        public string scountry { get; set; }
    }
}
