//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGradeLog
    {
        public int gradelogid { get; set; }
        public string bbcoursename { get; set; }
        public string bbcoursenum { get; set; }
        public string bbusername { get; set; }
        public string gsmucourseid { get; set; }
        public string gsmustudentid { get; set; }
        public string bbgrade { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
    }
}
