//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentValidation
    {
        public int StudentValidationId { get; set; }
        public string first { get; set; }
        public string last { get; set; }
        public string homephone { get; set; }
        public string workphone { get; set; }
        public string ExternalKey { get; set; }
    }
}
