//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsOtherInfoView
    {
        public string LOCATION { get; set; }
        public string SCHOOL { get; set; }
        public string GRADE { get; set; }
        public string DISTRICT { get; set; }
        public int STUDENTID { get; set; }
        public string STUDNUM { get; set; }
        public string StCompleteName { get; set; }
        public Nullable<double> ClockHoursSum { get; set; }
        public Nullable<double> CreditHoursSum { get; set; }
        public Nullable<double> InserviceHoursSum { get; set; }
        public Nullable<int> locationid { get; set; }
        public Nullable<int> GRADEID { get; set; }
        public Nullable<int> DISTID { get; set; }
    }
}
