//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuestionnaire
    {
        public int questID { get; set; }
        public string questiontext { get; set; }
        public Nullable<int> questiontype { get; set; }
        public Nullable<int> sortorder { get; set; }
        public Nullable<int> disabled { get; set; }
    }
}
