//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsGridComn
    {
        public string LOCATION { get; set; }
        public string GRADE { get; set; }
        public string DISTRICT { get; set; }
        public int STUDENTID { get; set; }
        public string STUDNUM { get; set; }
        public string FIRST { get; set; }
        public string LAST { get; set; }
        public string USERNAME { get; set; }
        public string SS { get; set; }
        public string EMAIL { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP { get; set; }
        public string COUNTRY { get; set; }
        public string HOMEPHONE { get; set; }
        public string WORKPHONE { get; set; }
        public string FAX { get; set; }
        public string EXPERIENCE { get; set; }
        public int InActive { get; set; }
        public string StudRegField1 { get; set; }
        public string StudRegField2 { get; set; }
        public string StudRegField3 { get; set; }
        public string StudRegField4 { get; set; }
        public string StudRegField5 { get; set; }
        public string StudRegField6 { get; set; }
        public string StudRegField7 { get; set; }
        public string StudRegField8 { get; set; }
        public string StudRegField9 { get; set; }
        public string StudRegField10 { get; set; }
        public short parentsid { get; set; }
        public Nullable<double> ClockHoursSum { get; set; }
        public Nullable<double> CreditHoursSum { get; set; }
        public Nullable<double> InserviceHoursSum { get; set; }
    }
}
