//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSite
    {
        public int SubSiteId { get; set; }
        public string SubSiteTitle { get; set; }
        public string SubSiteURL { get; set; }
        public string SubSiteCourseImportKey { get; set; }
        public Nullable<int> SubSitePrimary { get; set; }
        public Nullable<int> SubSiteHideCheckoutApproval { get; set; }
    }
}
