//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupervisorStudent
    {
        public int SupervisorID { get; set; }
        public int studentid { get; set; }
        public int supstudentid { get; set; }
    
        public virtual Supervisor Supervisor { get; set; }
    }
}
