//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class transcriptimport
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> classDate { get; set; }
        public string studnum { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Class { get; set; }
        public string Location { get; set; }
        public string School { get; set; }
        public string Attended { get; set; }
        public string Compensation { get; set; }
        public Nullable<double> Hours { get; set; }
        public string CODE { get; set; }
        public string coursename { get; set; }
        public string Instructor { get; set; }
    }
}
