//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcript
    {
        public int TranscriptID { get; set; }
        public Nullable<int> STUDENTID { get; set; }
        public string StudentsSchool { get; set; }
        public string District { get; set; }
        public string InstructorName { get; set; }
        public string InstructorName2 { get; set; }
        public string InstructorName3 { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string CourseNum { get; set; }
        public string CourseName { get; set; }
        public string CourseLocation { get; set; }
        public string CourseDate { get; set; }
        public Nullable<decimal> DistPrice { get; set; }
        public Nullable<decimal> NoDistPrice { get; set; }
        public string Room { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<double> CreditHours { get; set; }
        public string EventNum { get; set; }
        public string AccountNum { get; set; }
        public Nullable<System.DateTime> DATEADDED { get; set; }
        public Nullable<System.DateTime> TIMEADDED { get; set; }
        public short ATTENDED { get; set; }
        public short DIDNTATTEND { get; set; }
        public Nullable<double> HOURS { get; set; }
        public string CourseCost { get; set; }
        public string PAYMETHOD { get; set; }
        public string payNumber { get; set; }
        public string CardExp { get; set; }
        public string AuthNum { get; set; }
        public string OrderNumber { get; set; }
        public string TotalPaid { get; set; }
        public string PaymentNotes { get; set; }
        public Nullable<System.DateTime> ReminderSent { get; set; }
        public short PaidInFull { get; set; }
        public string Position { get; set; }
        public string Job { get; set; }
        public Nullable<System.DateTime> Reminder2Sent { get; set; }
        public string StudentGrade { get; set; }
        public string PricingOption { get; set; }
        public short PricingMember { get; set; }
        public double InserviceHours { get; set; }
        public string CourseHoursType { get; set; }
        public Nullable<short> UserEditedFlag { get; set; }
        public string CourseCategoryName { get; set; }
        public System.DateTime CourseCompletionDate { get; set; }
        public System.DateTime CourseStartDate { get; set; }
        public string Period { get; set; }
        public int LinkedTranscriptID { get; set; }
        public string AttendanceDetail { get; set; }
        public Nullable<double> CustomCreditHours { get; set; }
        public Nullable<float> graduatecredit { get; set; }
        public Nullable<float> ceucredit { get; set; }
        public string AttendanceStatus { get; set; }
        public string OptionalCollectedInfo1 { get; set; }
        public Nullable<int> RefundedAmount { get; set; }
        public Nullable<int> RefundDue { get; set; }
        public Nullable<float> Optionalcredithours1 { get; set; }
        public Nullable<int> onlinecourse { get; set; }
        public Nullable<System.DateTime> datemodified { get; set; }
        public Nullable<System.DateTime> datetranscribed { get; set; }
        public Nullable<int> UserAddedFlag { get; set; }
        public Nullable<System.DateTime> DateAutoCertSent { get; set; }
        public string districtaddressinfo { get; set; }
        public string schooladdressinfo { get; set; }
        public string gradeaddressinfo { get; set; }
        public Nullable<System.DateTime> CertificateIssueDate { get; set; }
        public string districtaddressinfo2 { get; set; }
        public string schooladdressinfo2 { get; set; }
        public Nullable<int> studrosterid { get; set; }
        public Nullable<int> IsHoursPaid { get; set; }
        public Nullable<double> Optionalcredithours2 { get; set; }
        public Nullable<double> Optionalcredithours3 { get; set; }
        public Nullable<double> Optionalcredithours4 { get; set; }
        public Nullable<double> Optionalcredithours5 { get; set; }
        public Nullable<double> Optionalcredithours6 { get; set; }
        public Nullable<double> Optionalcredithours7 { get; set; }
        public Nullable<double> Optionalcredithours8 { get; set; }
        public string IsHoursPaidInfo { get; set; }
    
        public virtual Course Cours { get; set; }
        public virtual Student Student { get; set; }
    }
}
