//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class uploadedfile
    {
        public int uploadid { get; set; }
        public string ufilename { get; set; }
        public string udescription { get; set; }
        public Nullable<int> uorder { get; set; }
        public Nullable<int> udisabled { get; set; }
        public Nullable<int> udownloaded { get; set; }
        public Nullable<System.DateTime> udateadded { get; set; }
    }
}
