//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBBDateInformation
    {
        public int idx { get; set; }
        public Nullable<int> userid { get; set; }
        public string susername { get; set; }
        public Nullable<System.DateTime> sdate_modified { get; set; }
        public Nullable<System.DateTime> sdate_bb_integrated { get; set; }
        public Nullable<int> usertype { get; set; }
        public Nullable<int> bbserverid { get; set; }
    }
}
