//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WizardConfiguration
    {
        public int WizardConfigID { get; set; }
        public string WizardHeader { get; set; }
        public string WizardInstrutions { get; set; }
        public Nullable<int> WizardPosition { get; set; }
        public string WizardFunction { get; set; }
    }
}
