//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.ClientTracking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assessment
    {
        public int id { get; set; }
        public Nullable<System.DateTime> assessment_date { get; set; }
        public Nullable<int> points_earned { get; set; }
        public Nullable<int> possible_points { get; set; }
        public string user_ip { get; set; }
    }
}
