//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.ClientTracking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GosignmeupStudentCount
    {
        public int GSCID { get; set; }
        public string GSCClientName { get; set; }
        public string GSCClientDomainName { get; set; }
        public System.DateTime GSCInsertDate { get; set; }
        public int GSCStudentCount { get; set; }
    }
}
