//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.ClientTracking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsletterTag
    {
        public long NewsletterTagUId { get; set; }
        public string Tag { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long NewsletterId { get; set; }
    
        public virtual Newsletter Newsletter { get; set; }
    }
}
