//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.ClientTracking.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceStat
    {
        public int PerformanceStatsId { get; set; }
        public string ClientName { get; set; }
        public string RoutineName { get; set; }
        public Nullable<float> ServerSeconds { get; set; }
        public Nullable<float> ClientSeconds { get; set; }
        public Nullable<System.DateTime> DateTimeRan { get; set; }
    }
}
