//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.Data.School.Entities
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    using Gsmu.Api.Data;

    public partial class School
    {
        public static int NextId
        {
            get 
            {
                using (var db = Connections.GetSchoolConnection())
                {
                    db.Open();
                    var query = "select max(locationid) + 1 from schools";
                    var cmd = db.CreateCommand();
                    cmd.CommandText = query;
                    var result = cmd.ExecuteScalar();
                    db.Close();
                    if (result == System.DBNull.Value)
                    {
                        return 1;
                    }
                    return (int)result;                    
                }
            }
        }

        public int ActiveStudents
        {
            get
            {
                if (!this.locationid.HasValue) {
                    return 0;
                }
                using (var db = new SchoolEntities())
                {
                    var count = (from s in db.Students where s.SCHOOL == this.locationid.Value select s).Count();
                    return count;
                }
            }
        }

    }
}
