//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gsmu.Api.TCSOnlineService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class TCSServiceFault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string return_codeField;
        
        private string return_detailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string return_code {
            get {
                return this.return_codeField;
            }
            set {
                this.return_codeField = value;
                this.RaisePropertyChanged("return_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string return_detail {
            get {
                return this.return_detailField;
            }
            set {
                this.return_detailField = value;
                this.RaisePropertyChanged("return_detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class StartOnlineCollectionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class classificationData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string classification_idField;
        
        private decimal amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string classification_id {
            get {
                return this.classification_idField;
            }
            set {
                this.classification_idField = value;
                this.RaisePropertyChanged("classification_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CustomCollectionFields : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string custom_field_1Field;
        
        private string custom_field_2Field;
        
        private string custom_field_3Field;
        
        private string custom_field_4Field;
        
        private string custom_field_5Field;
        
        private string custom_field_6Field;
        
        private string custom_field_7Field;
        
        private string custom_field_8Field;
        
        private string custom_field_9Field;
        
        private string custom_field_10Field;
        
        private string custom_field_11Field;
        
        private string custom_field_12Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string custom_field_1 {
            get {
                return this.custom_field_1Field;
            }
            set {
                this.custom_field_1Field = value;
                this.RaisePropertyChanged("custom_field_1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string custom_field_2 {
            get {
                return this.custom_field_2Field;
            }
            set {
                this.custom_field_2Field = value;
                this.RaisePropertyChanged("custom_field_2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string custom_field_3 {
            get {
                return this.custom_field_3Field;
            }
            set {
                this.custom_field_3Field = value;
                this.RaisePropertyChanged("custom_field_3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string custom_field_4 {
            get {
                return this.custom_field_4Field;
            }
            set {
                this.custom_field_4Field = value;
                this.RaisePropertyChanged("custom_field_4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string custom_field_5 {
            get {
                return this.custom_field_5Field;
            }
            set {
                this.custom_field_5Field = value;
                this.RaisePropertyChanged("custom_field_5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string custom_field_6 {
            get {
                return this.custom_field_6Field;
            }
            set {
                this.custom_field_6Field = value;
                this.RaisePropertyChanged("custom_field_6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string custom_field_7 {
            get {
                return this.custom_field_7Field;
            }
            set {
                this.custom_field_7Field = value;
                this.RaisePropertyChanged("custom_field_7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string custom_field_8 {
            get {
                return this.custom_field_8Field;
            }
            set {
                this.custom_field_8Field = value;
                this.RaisePropertyChanged("custom_field_8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string custom_field_9 {
            get {
                return this.custom_field_9Field;
            }
            set {
                this.custom_field_9Field = value;
                this.RaisePropertyChanged("custom_field_9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string custom_field_10 {
            get {
                return this.custom_field_10Field;
            }
            set {
                this.custom_field_10Field = value;
                this.RaisePropertyChanged("custom_field_10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string custom_field_11 {
            get {
                return this.custom_field_11Field;
            }
            set {
                this.custom_field_11Field = value;
                this.RaisePropertyChanged("custom_field_11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string custom_field_12 {
            get {
                return this.custom_field_12Field;
            }
            set {
                this.custom_field_12Field = value;
                this.RaisePropertyChanged("custom_field_12");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class StartOnlineCollectionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tcs_app_idField;
        
        private string agency_tracking_idField;
        
        private TransactionType transaction_typeField;
        
        private decimal transaction_amountField;
        
        private string languageField;
        
        private string url_successField;
        
        private string url_cancelField;
        
        private string account_holder_nameField;
        
        private string billing_addressField;
        
        private string billing_address2Field;
        
        private string billing_cityField;
        
        private string billing_stateField;
        
        private string billing_zipField;
        
        private string billing_countryField;
        
        private string email_addressField;
        
        private CustomCollectionFields custom_fieldsField;
        
        private classificationData[] classificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agency_tracking_id {
            get {
                return this.agency_tracking_idField;
            }
            set {
                this.agency_tracking_idField = value;
                this.RaisePropertyChanged("agency_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public TransactionType transaction_type {
            get {
                return this.transaction_typeField;
            }
            set {
                this.transaction_typeField = value;
                this.RaisePropertyChanged("transaction_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=5)]
        public string url_success {
            get {
                return this.url_successField;
            }
            set {
                this.url_successField = value;
                this.RaisePropertyChanged("url_success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=6)]
        public string url_cancel {
            get {
                return this.url_cancelField;
            }
            set {
                this.url_cancelField = value;
                this.RaisePropertyChanged("url_cancel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string account_holder_name {
            get {
                return this.account_holder_nameField;
            }
            set {
                this.account_holder_nameField = value;
                this.RaisePropertyChanged("account_holder_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string billing_address {
            get {
                return this.billing_addressField;
            }
            set {
                this.billing_addressField = value;
                this.RaisePropertyChanged("billing_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string billing_address2 {
            get {
                return this.billing_address2Field;
            }
            set {
                this.billing_address2Field = value;
                this.RaisePropertyChanged("billing_address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string billing_city {
            get {
                return this.billing_cityField;
            }
            set {
                this.billing_cityField = value;
                this.RaisePropertyChanged("billing_city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string billing_state {
            get {
                return this.billing_stateField;
            }
            set {
                this.billing_stateField = value;
                this.RaisePropertyChanged("billing_state");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string billing_zip {
            get {
                return this.billing_zipField;
            }
            set {
                this.billing_zipField = value;
                this.RaisePropertyChanged("billing_zip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string billing_country {
            get {
                return this.billing_countryField;
            }
            set {
                this.billing_countryField = value;
                this.RaisePropertyChanged("billing_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string email_address {
            get {
                return this.email_addressField;
            }
            set {
                this.email_addressField = value;
                this.RaisePropertyChanged("email_address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public CustomCollectionFields custom_fields {
            get {
                return this.custom_fieldsField;
            }
            set {
                this.custom_fieldsField = value;
                this.RaisePropertyChanged("custom_fields");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification_data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public classificationData[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public enum TransactionType {
        
        /// <remarks/>
        Authorization,
        
        /// <remarks/>
        Sale,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fms.treas.gov/services/tcsonline", ConfigurationName="TCSOnlineService.TCSOnlineService")]
    public interface TCSOnlineService {
        
        // CODEGEN: Parameter 'startOnlineCollectionResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="startOnlineCollectionResponse")]
        Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1 startOnlineCollection(Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1> startOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 request);
        
        // CODEGEN: Parameter 'completeOnlineCollectionResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="completeOnlineCollectionResponse")]
        Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1 completeOnlineCollection(Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1> completeOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 request);
        
        // CODEGEN: Parameter 'completeOnlineCollectionWithDetailsResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="completeOnlineCollectionWithDetailsResponse")]
        Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1 completeOnlineCollectionWithDetails(Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1> completeOnlineCollectionWithDetailsAsync(Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 request);
        
        // CODEGEN: Parameter 'createForceResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createForceResponse")]
        Gsmu.Api.TCSOnlineService.createForceResponse1 createForce(Gsmu.Api.TCSOnlineService.createForceRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceResponse1> createForceAsync(Gsmu.Api.TCSOnlineService.createForceRequest1 request);
        
        // CODEGEN: Parameter 'createForceWithDetailsResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="createForceWithDetailsResponse")]
        Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1 createForceWithDetails(Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1> createForceWithDetailsAsync(Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 request);
        
        // CODEGEN: Parameter 'getDetailsResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gsmu.Api.TCSOnlineService.TCSServiceFault), Action="", Name="TCSServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="getDetailsResponse")]
        Gsmu.Api.TCSOnlineService.getDetailsResponse1 getDetails(Gsmu.Api.TCSOnlineService.getDetailsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.getDetailsResponse1> getDetailsAsync(Gsmu.Api.TCSOnlineService.getDetailsRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startOnlineCollection", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class startOnlineCollectionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.StartOnlineCollectionRequest startOnlineCollectionRequest;
        
        public startOnlineCollectionRequest1() {
        }
        
        public startOnlineCollectionRequest1(Gsmu.Api.TCSOnlineService.StartOnlineCollectionRequest startOnlineCollectionRequest) {
            this.startOnlineCollectionRequest = startOnlineCollectionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="startOnlineCollectionResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class startOnlineCollectionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.StartOnlineCollectionResponse startOnlineCollectionResponse;
        
        public startOnlineCollectionResponse1() {
        }
        
        public startOnlineCollectionResponse1(Gsmu.Api.TCSOnlineService.StartOnlineCollectionResponse startOnlineCollectionResponse) {
            this.startOnlineCollectionResponse = startOnlineCollectionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CompleteOnlineCollectionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tcs_app_idField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CompleteOnlineCollectionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paygov_tracking_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paygov_tracking_id {
            get {
                return this.paygov_tracking_idField;
            }
            set {
                this.paygov_tracking_idField = value;
                this.RaisePropertyChanged("paygov_tracking_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeOnlineCollection", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class completeOnlineCollectionRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionRequest completeOnlineCollectionRequest;
        
        public completeOnlineCollectionRequest1() {
        }
        
        public completeOnlineCollectionRequest1(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionRequest completeOnlineCollectionRequest) {
            this.completeOnlineCollectionRequest = completeOnlineCollectionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeOnlineCollectionResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class completeOnlineCollectionResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionResponse completeOnlineCollectionResponse;
        
        public completeOnlineCollectionResponse1() {
        }
        
        public completeOnlineCollectionResponse1(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionResponse completeOnlineCollectionResponse) {
            this.completeOnlineCollectionResponse = completeOnlineCollectionResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CompleteOnlineCollectionWithDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tcs_app_idField;
        
        private string tokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
                this.RaisePropertyChanged("token");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CompleteOnlineCollectionWithDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paygov_tracking_idField;
        
        private string agency_tracking_idField;
        
        private decimal transaction_amountField;
        
        private string transaction_typeField;
        
        private System.DateTime transaction_dateField;
        
        private System.DateTime payment_dateField;
        
        private bool payment_dateFieldSpecified;
        
        private string transaction_statusField;
        
        private PaymentType payment_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paygov_tracking_id {
            get {
                return this.paygov_tracking_idField;
            }
            set {
                this.paygov_tracking_idField = value;
                this.RaisePropertyChanged("paygov_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agency_tracking_id {
            get {
                return this.agency_tracking_idField;
            }
            set {
                this.agency_tracking_idField = value;
                this.RaisePropertyChanged("agency_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transaction_type {
            get {
                return this.transaction_typeField;
            }
            set {
                this.transaction_typeField = value;
                this.RaisePropertyChanged("transaction_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                this.transaction_dateField = value;
                this.RaisePropertyChanged("transaction_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime payment_date {
            get {
                return this.payment_dateField;
            }
            set {
                this.payment_dateField = value;
                this.RaisePropertyChanged("payment_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payment_dateSpecified {
            get {
                return this.payment_dateFieldSpecified;
            }
            set {
                this.payment_dateFieldSpecified = value;
                this.RaisePropertyChanged("payment_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transaction_status {
            get {
                return this.transaction_statusField;
            }
            set {
                this.transaction_statusField = value;
                this.RaisePropertyChanged("transaction_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public PaymentType payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
                this.RaisePropertyChanged("payment_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public enum PaymentType {
        
        /// <remarks/>
        PLASTIC_CARD,
        
        /// <remarks/>
        ACH,
        
        /// <remarks/>
        ACH_CREDIT,
        
        /// <remarks/>
        AMAZON,
        
        /// <remarks/>
        PAYPAL,
        
        /// <remarks/>
        DWOLLA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeOnlineCollectionWithDetails", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class completeOnlineCollectionWithDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsRequest completeOnlineCollectionWithDetailsRequest;
        
        public completeOnlineCollectionWithDetailsRequest1() {
        }
        
        public completeOnlineCollectionWithDetailsRequest1(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsRequest completeOnlineCollectionWithDetailsRequest) {
            this.completeOnlineCollectionWithDetailsRequest = completeOnlineCollectionWithDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="completeOnlineCollectionWithDetailsResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class completeOnlineCollectionWithDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsResponse completeOnlineCollectionWithDetailsResponse;
        
        public completeOnlineCollectionWithDetailsResponse1() {
        }
        
        public completeOnlineCollectionWithDetailsResponse1(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsResponse completeOnlineCollectionWithDetailsResponse) {
            this.completeOnlineCollectionWithDetailsResponse = completeOnlineCollectionWithDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CreateForceRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        private string tcs_app_idField;
        
        private decimal transaction_amountField;
        
        private classificationData[] classificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agency_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("paygov_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification_data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public classificationData[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":agency_tracking_id")]
        agency_tracking_id,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":paygov_tracking_id")]
        paygov_tracking_id,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CreateForceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paygov_tracking_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paygov_tracking_id {
            get {
                return this.paygov_tracking_idField;
            }
            set {
                this.paygov_tracking_idField = value;
                this.RaisePropertyChanged("paygov_tracking_id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createForce", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class createForceRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CreateForceRequest createForceRequest;
        
        public createForceRequest1() {
        }
        
        public createForceRequest1(Gsmu.Api.TCSOnlineService.CreateForceRequest createForceRequest) {
            this.createForceRequest = createForceRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createForceResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class createForceResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CreateForceResponse createForceResponse;
        
        public createForceResponse1() {
        }
        
        public createForceResponse1(Gsmu.Api.TCSOnlineService.CreateForceResponse createForceResponse) {
            this.createForceResponse = createForceResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CreateForceWithDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        private string tcs_app_idField;
        
        private decimal transaction_amountField;
        
        private classificationData[] classificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agency_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("paygov_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification_data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public classificationData[] classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
                this.RaisePropertyChanged("classification");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":agency_tracking_id")]
        agency_tracking_id,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":paygov_tracking_id")]
        paygov_tracking_id,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class CreateForceWithDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paygov_tracking_idField;
        
        private string agency_tracking_idField;
        
        private decimal transaction_amountField;
        
        private string transaction_typeField;
        
        private System.DateTime transaction_dateField;
        
        private System.DateTime payment_dateField;
        
        private bool payment_dateFieldSpecified;
        
        private string transaction_statusField;
        
        private PaymentType payment_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paygov_tracking_id {
            get {
                return this.paygov_tracking_idField;
            }
            set {
                this.paygov_tracking_idField = value;
                this.RaisePropertyChanged("paygov_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agency_tracking_id {
            get {
                return this.agency_tracking_idField;
            }
            set {
                this.agency_tracking_idField = value;
                this.RaisePropertyChanged("agency_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transaction_type {
            get {
                return this.transaction_typeField;
            }
            set {
                this.transaction_typeField = value;
                this.RaisePropertyChanged("transaction_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                this.transaction_dateField = value;
                this.RaisePropertyChanged("transaction_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime payment_date {
            get {
                return this.payment_dateField;
            }
            set {
                this.payment_dateField = value;
                this.RaisePropertyChanged("payment_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payment_dateSpecified {
            get {
                return this.payment_dateFieldSpecified;
            }
            set {
                this.payment_dateFieldSpecified = value;
                this.RaisePropertyChanged("payment_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transaction_status {
            get {
                return this.transaction_statusField;
            }
            set {
                this.transaction_statusField = value;
                this.RaisePropertyChanged("transaction_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public PaymentType payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
                this.RaisePropertyChanged("payment_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createForceWithDetails", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class createForceWithDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CreateForceWithDetailsRequest createForceWithDetailsRequest;
        
        public createForceWithDetailsRequest1() {
        }
        
        public createForceWithDetailsRequest1(Gsmu.Api.TCSOnlineService.CreateForceWithDetailsRequest createForceWithDetailsRequest) {
            this.createForceWithDetailsRequest = createForceWithDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createForceWithDetailsResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class createForceWithDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.CreateForceWithDetailsResponse createForceWithDetailsResponse;
        
        public createForceWithDetailsResponse1() {
        }
        
        public createForceWithDetailsResponse1(Gsmu.Api.TCSOnlineService.CreateForceWithDetailsResponse createForceWithDetailsResponse) {
            this.createForceWithDetailsResponse = createForceWithDetailsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class GetDetailsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tcs_app_idField;
        
        private string itemField;
        
        private ItemChoiceType2 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tcs_app_id {
            get {
                return this.tcs_app_idField;
            }
            set {
                this.tcs_app_idField = value;
                this.RaisePropertyChanged("tcs_app_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agency_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("paygov_tracking_id", typeof(string), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType2 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline", IncludeInSchema=false)]
    public enum ItemChoiceType2 {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":agency_tracking_id")]
        agency_tracking_id,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute(":paygov_tracking_id")]
        paygov_tracking_id,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class GetDetailsResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private transactionData[] transactionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public transactionData[] transactions {
            get {
                return this.transactionsField;
            }
            set {
                this.transactionsField = value;
                this.RaisePropertyChanged("transactions");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fms.treas.gov/services/tcsonline")]
    public partial class transactionData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paygov_tracking_idField;
        
        private string agency_tracking_idField;
        
        private decimal transaction_amountField;
        
        private string transaction_typeField;
        
        private System.DateTime transaction_dateField;
        
        private System.DateTime payment_dateField;
        
        private bool payment_dateFieldSpecified;
        
        private string transaction_statusField;
        
        private PaymentType payment_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string paygov_tracking_id {
            get {
                return this.paygov_tracking_idField;
            }
            set {
                this.paygov_tracking_idField = value;
                this.RaisePropertyChanged("paygov_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string agency_tracking_id {
            get {
                return this.agency_tracking_idField;
            }
            set {
                this.agency_tracking_idField = value;
                this.RaisePropertyChanged("agency_tracking_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal transaction_amount {
            get {
                return this.transaction_amountField;
            }
            set {
                this.transaction_amountField = value;
                this.RaisePropertyChanged("transaction_amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string transaction_type {
            get {
                return this.transaction_typeField;
            }
            set {
                this.transaction_typeField = value;
                this.RaisePropertyChanged("transaction_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime transaction_date {
            get {
                return this.transaction_dateField;
            }
            set {
                this.transaction_dateField = value;
                this.RaisePropertyChanged("transaction_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime payment_date {
            get {
                return this.payment_dateField;
            }
            set {
                this.payment_dateField = value;
                this.RaisePropertyChanged("payment_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool payment_dateSpecified {
            get {
                return this.payment_dateFieldSpecified;
            }
            set {
                this.payment_dateFieldSpecified = value;
                this.RaisePropertyChanged("payment_dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string transaction_status {
            get {
                return this.transaction_statusField;
            }
            set {
                this.transaction_statusField = value;
                this.RaisePropertyChanged("transaction_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public PaymentType payment_type {
            get {
                return this.payment_typeField;
            }
            set {
                this.payment_typeField = value;
                this.RaisePropertyChanged("payment_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDetails", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class getDetailsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.GetDetailsRequest getDetailsRequest;
        
        public getDetailsRequest1() {
        }
        
        public getDetailsRequest1(Gsmu.Api.TCSOnlineService.GetDetailsRequest getDetailsRequest) {
            this.getDetailsRequest = getDetailsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDetailsResponse", WrapperNamespace="http://fms.treas.gov/services/tcsonline", IsWrapped=true)]
    public partial class getDetailsResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fms.treas.gov/services/tcsonline", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Gsmu.Api.TCSOnlineService.GetDetailsResponse getDetailsResponse;
        
        public getDetailsResponse1() {
        }
        
        public getDetailsResponse1(Gsmu.Api.TCSOnlineService.GetDetailsResponse getDetailsResponse) {
            this.getDetailsResponse = getDetailsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TCSOnlineServiceChannel : Gsmu.Api.TCSOnlineService.TCSOnlineService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TCSOnlineServiceClient : System.ServiceModel.ClientBase<Gsmu.Api.TCSOnlineService.TCSOnlineService>, Gsmu.Api.TCSOnlineService.TCSOnlineService {
        
        public TCSOnlineServiceClient() {
        }
        
        public TCSOnlineServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TCSOnlineServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCSOnlineServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TCSOnlineServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.startOnlineCollection(Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 request) {
            return base.Channel.startOnlineCollection(request);
        }
        
        public Gsmu.Api.TCSOnlineService.StartOnlineCollectionResponse startOnlineCollection(Gsmu.Api.TCSOnlineService.StartOnlineCollectionRequest startOnlineCollectionRequest) {
            Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 inValue = new Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1();
            inValue.startOnlineCollectionRequest = startOnlineCollectionRequest;
            Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).startOnlineCollection(inValue);
            return retVal.startOnlineCollectionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.startOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 request) {
            return base.Channel.startOnlineCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.startOnlineCollectionResponse1> startOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.StartOnlineCollectionRequest startOnlineCollectionRequest) {
            Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1 inValue = new Gsmu.Api.TCSOnlineService.startOnlineCollectionRequest1();
            inValue.startOnlineCollectionRequest = startOnlineCollectionRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).startOnlineCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.completeOnlineCollection(Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 request) {
            return base.Channel.completeOnlineCollection(request);
        }
        
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionResponse completeOnlineCollection(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionRequest completeOnlineCollectionRequest) {
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 inValue = new Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1();
            inValue.completeOnlineCollectionRequest = completeOnlineCollectionRequest;
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).completeOnlineCollection(inValue);
            return retVal.completeOnlineCollectionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.completeOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 request) {
            return base.Channel.completeOnlineCollectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionResponse1> completeOnlineCollectionAsync(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionRequest completeOnlineCollectionRequest) {
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1 inValue = new Gsmu.Api.TCSOnlineService.completeOnlineCollectionRequest1();
            inValue.completeOnlineCollectionRequest = completeOnlineCollectionRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).completeOnlineCollectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.completeOnlineCollectionWithDetails(Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 request) {
            return base.Channel.completeOnlineCollectionWithDetails(request);
        }
        
        public Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsResponse completeOnlineCollectionWithDetails(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsRequest completeOnlineCollectionWithDetailsRequest) {
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1();
            inValue.completeOnlineCollectionWithDetailsRequest = completeOnlineCollectionWithDetailsRequest;
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).completeOnlineCollectionWithDetails(inValue);
            return retVal.completeOnlineCollectionWithDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.completeOnlineCollectionWithDetailsAsync(Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 request) {
            return base.Channel.completeOnlineCollectionWithDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsResponse1> completeOnlineCollectionWithDetailsAsync(Gsmu.Api.TCSOnlineService.CompleteOnlineCollectionWithDetailsRequest completeOnlineCollectionWithDetailsRequest) {
            Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.completeOnlineCollectionWithDetailsRequest1();
            inValue.completeOnlineCollectionWithDetailsRequest = completeOnlineCollectionWithDetailsRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).completeOnlineCollectionWithDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.createForceResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.createForce(Gsmu.Api.TCSOnlineService.createForceRequest1 request) {
            return base.Channel.createForce(request);
        }
        
        public Gsmu.Api.TCSOnlineService.CreateForceResponse createForce(Gsmu.Api.TCSOnlineService.CreateForceRequest createForceRequest) {
            Gsmu.Api.TCSOnlineService.createForceRequest1 inValue = new Gsmu.Api.TCSOnlineService.createForceRequest1();
            inValue.createForceRequest = createForceRequest;
            Gsmu.Api.TCSOnlineService.createForceResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).createForce(inValue);
            return retVal.createForceResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.createForceAsync(Gsmu.Api.TCSOnlineService.createForceRequest1 request) {
            return base.Channel.createForceAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceResponse1> createForceAsync(Gsmu.Api.TCSOnlineService.CreateForceRequest createForceRequest) {
            Gsmu.Api.TCSOnlineService.createForceRequest1 inValue = new Gsmu.Api.TCSOnlineService.createForceRequest1();
            inValue.createForceRequest = createForceRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).createForceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.createForceWithDetails(Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 request) {
            return base.Channel.createForceWithDetails(request);
        }
        
        public Gsmu.Api.TCSOnlineService.CreateForceWithDetailsResponse createForceWithDetails(Gsmu.Api.TCSOnlineService.CreateForceWithDetailsRequest createForceWithDetailsRequest) {
            Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1();
            inValue.createForceWithDetailsRequest = createForceWithDetailsRequest;
            Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).createForceWithDetails(inValue);
            return retVal.createForceWithDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.createForceWithDetailsAsync(Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 request) {
            return base.Channel.createForceWithDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.createForceWithDetailsResponse1> createForceWithDetailsAsync(Gsmu.Api.TCSOnlineService.CreateForceWithDetailsRequest createForceWithDetailsRequest) {
            Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.createForceWithDetailsRequest1();
            inValue.createForceWithDetailsRequest = createForceWithDetailsRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).createForceWithDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gsmu.Api.TCSOnlineService.getDetailsResponse1 Gsmu.Api.TCSOnlineService.TCSOnlineService.getDetails(Gsmu.Api.TCSOnlineService.getDetailsRequest1 request) {
            return base.Channel.getDetails(request);
        }
        
        public Gsmu.Api.TCSOnlineService.GetDetailsResponse getDetails(Gsmu.Api.TCSOnlineService.GetDetailsRequest getDetailsRequest) {
            Gsmu.Api.TCSOnlineService.getDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.getDetailsRequest1();
            inValue.getDetailsRequest = getDetailsRequest;
            Gsmu.Api.TCSOnlineService.getDetailsResponse1 retVal = ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).getDetails(inValue);
            return retVal.getDetailsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.getDetailsResponse1> Gsmu.Api.TCSOnlineService.TCSOnlineService.getDetailsAsync(Gsmu.Api.TCSOnlineService.getDetailsRequest1 request) {
            return base.Channel.getDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gsmu.Api.TCSOnlineService.getDetailsResponse1> getDetailsAsync(Gsmu.Api.TCSOnlineService.GetDetailsRequest getDetailsRequest) {
            Gsmu.Api.TCSOnlineService.getDetailsRequest1 inValue = new Gsmu.Api.TCSOnlineService.getDetailsRequest1();
            inValue.getDetailsRequest = getDetailsRequest;
            return ((Gsmu.Api.TCSOnlineService.TCSOnlineService)(this)).getDetailsAsync(inValue);
        }
    }
}
